<?php
$_grade = array (
  'supper' => 
  array (
    'kid' => 'supper',
    'model' => 'adminer',
    'title' => '超级管理员',
    'defmu' => 'm1coms',
    'impid' => '',
    'pmadm' => '',
    'pmusr' => 'm1base,m2uedit,m2upass,m2uinfo,m2utips,m1order,m2order,m2oitem,m2oquiry,m1docs,m2idview,m2idpub',
    'mkva' => '',
    'mkvu' => '',
    'pfile' => '',
    'pmod' => '',
    'padd' => '',
    'pdel' => '',
    'pcheck' => '',
    'pextra' => '',
    'cfgs' => '',
    'grade' => 'supper',
  ),
  'ainfo' => 
  array (
    'kid' => 'ainfo',
    'model' => 'adminer',
    'title' => '信息管理员',
    'defmu' => 'm1info',
    'impid' => '',
    'pmadm' => 'm1012,m1main,m1info,m1coms,m1tool,m2test1,m3demo,m3drem,m2test2,m3b3,m3b1,m3b2,m2pro,m3order,m3pro,m3cset,m2res,m3kres,m3keres,m2user,m2info,m3news,m3nrem,m3about,m2topic,m3topic,m3torem,m2indoc,m3indoc,m3inread,m3inrem,m3inmem,m2faqs,m3qadmin,m3qrtag,m3qaset,m2vote,m3vtadm,m3voip,m2else,m3gbook,m3notea,m2sys,m3catch,m3self,m2fav,m3favor',
    'pmusr' => 'order-isdone,indoc-get,indoc-d,indoc-adm',
    'mkva' => 'dops-m,dops-a,admin-catalog,admin-grade,admin-static,admin-uinfo,admin-update,apis-exp_indoc,apis-exp_order,apis-exp_qaset',
    'mkvu' => '',
    'pfile' => 'admin/paras.php,admin/api400.php',
    'pmod' => 'demo,about,news,cargo,topic,keres,indoc,votes,faqs,gbook,notea,inrem,inread,crem,drem,kerem,nrem,trem,corder,coitem,cocar,qarep,qatag,votei,votep,adfavor',
    'padd' => '',
    'pdel' => '',
    'pcheck' => '',
    'pextra' => 'edtlist,edtup,edtadm,pstools,psdev,image,flash,media,file',
    'cfgs' => 'upsize1=200
upsizes=960000',
    'grade' => 'ainfo',
  ),
  'aiadm' => 
  array (
    'kid' => 'aiadm',
    'model' => 'adminer',
    'title' => '信息主管',
    'defmu' => 'm1info',
    'impid' => 'ainfo',
    'pmadm' => 'm3env,m3ediy',
    'pmusr' => '',
    'mkva' => '',
    'mkvu' => '',
    'pfile' => '',
    'pmod' => '',
    'padd' => '',
    'pdel' => '',
    'pcheck' => '',
    'pextra' => '',
    'cfgs' => '',
    'grade' => 'aiadm',
  ),
  'auser' => 
  array (
    'kid' => 'auser',
    'model' => 'adminer',
    'title' => '会员管理员',
    'defmu' => '',
    'impid' => '',
    'pmadm' => '',
    'pmusr' => 'm1base,m2uedit,m2upass,m2uinfo,m2utips,m1order,m2order,m2oitem,m2oquiry,m1docs,m2idview,m2idpub',
    'mkva' => '',
    'mkvu' => '',
    'pfile' => '',
    'pmod' => '',
    'padd' => '',
    'pdel' => '',
    'pcheck' => '',
    'pextra' => '',
    'cfgs' => '',
    'grade' => 'auser',
  ),
  'advers' => 
  array (
    'kid' => 'advers',
    'model' => 'adminer',
    'title' => '广告管理员',
    'defmu' => '',
    'impid' => '',
    'pmadm' => '',
    'pmusr' => 'm1base,m2uedit,m2upass,m2uinfo,m2utips,m1order,m2order,m2oitem,m2oquiry,m1docs,m2idview,m2idpub',
    'mkva' => '',
    'mkvu' => '',
    'pfile' => '',
    'pmod' => '',
    'padd' => '',
    'pdel' => '',
    'pcheck' => '',
    'pextra' => '',
    'cfgs' => '',
    'grade' => 'advers',
  ),
  'aframe' => 
  array (
    'kid' => 'aframe',
    'model' => 'adminer',
    'title' => '系统架构员',
    'defmu' => '',
    'impid' => '',
    'pmadm' => '',
    'pmusr' => 'm1base,m2uedit,m2upass,m2uinfo,m2utips,m1order,m2order,m2oitem,m2oquiry,m1docs,m2idview,m2idpub',
    'mkva' => '',
    'mkvu' => '',
    'pfile' => '',
    'pmod' => '',
    'padd' => '',
    'pdel' => '',
    'pcheck' => '',
    'pextra' => '',
    'cfgs' => '',
    'grade' => 'aframe',
  ),
  'aperm' => 
  array (
    'kid' => 'aperm',
    'model' => 'adminer',
    'title' => '权限测试员',
    'defmu' => '',
    'impid' => '',
    'pmadm' => 'm1edu,m1inf',
    'pmusr' => 'm1base,m2uedit,m2upass,m2uinfo,m2utips,m1order,m2order,m2oitem,m2oquiry,m1docs,m2idview,m2idpub',
    'mkva' => '',
    'mkvu' => '',
    'pfile' => 'admin/menus.php,admin/apisms.php',
    'pmod' => 'demo,nrem',
    'padd' => 'about,gbook',
    'pdel' => 'news,snote',
    'pcheck' => 'pro',
    'pextra' => 'edtlist,edtup,edtadm',
    'cfgs' => '',
    'grade' => 'aperm',
  ),
  'astop' => 
  array (
    'kid' => 'astop',
    'model' => 'adminer',
    'title' => '过期管理员',
    'defmu' => '',
    'impid' => '',
    'pmadm' => '',
    'pmusr' => 'm1base,m2uedit,m2upass,m2uinfo,m2utips,m1order,m2order,m2oitem,m2oquiry,m1docs,m2idview,m2idpub',
    'mkva' => '',
    'mkvu' => '',
    'pfile' => '',
    'pmod' => '',
    'padd' => '',
    'pdel' => '',
    'pcheck' => '',
    'pextra' => '',
    'cfgs' => '',
    'grade' => 'astop',
  ),
  'ccom' => 
  array (
    'kid' => 'ccom',
    'model' => 'company',
    'title' => '普通企业',
    'defmu' => '',
    'impid' => '',
    'pmadm' => '',
    'pmusr' => 'm1base,m2uedit,m2upass,m2uinfo,m2utips,m1order,m2order,m2oitem,m2oquiry,m1docs,m2idview,m2idpub',
    'mkva' => '',
    'mkvu' => '',
    'pfile' => '',
    'pmod' => 'demo,about',
    'padd' => '',
    'pdel' => '',
    'pcheck' => '',
    'pextra' => 'edtlist,edtup,edtadm,pstools,psdev,image,flash,media,docus',
    'cfgs' => 'upsize1=200
upsizes=960000',
    'grade' => 'ccom',
  ),
  'cvip' => 
  array (
    'kid' => 'cvip',
    'model' => 'company',
    'title' => 'VIP企业',
    'defmu' => '',
    'impid' => '',
    'pmadm' => '',
    'pmusr' => 'm1base,m2uedit,m2upass,m2uinfo,m2utips,m1order,m2order,m2oitem,m2oquiry,m1docs,m2idview,m2idpub',
    'mkva' => '',
    'mkvu' => '',
    'pfile' => '',
    'pmod' => '',
    'padd' => '',
    'pdel' => '',
    'pcheck' => '',
    'pextra' => 'edtlist,edtup,edtadm',
    'cfgs' => 'tplname=corp/mem-detailvip
tplnamenews=corp/mem-ulstvip',
    'grade' => 'cvip',
  ),
  'cstop' => 
  array (
    'kid' => 'cstop',
    'model' => 'company',
    'title' => '过期企业',
    'defmu' => '',
    'impid' => '',
    'pmadm' => '',
    'pmusr' => 'm1base,m2uedit,m2upass,m2uinfo,m2utips,m1order,m2order,m2oitem,m2oquiry,m1docs,m2idview,m2idpub',
    'mkva' => '',
    'mkvu' => '',
    'pfile' => '',
    'pmod' => '',
    'padd' => '',
    'pdel' => '',
    'pcheck' => '',
    'pextra' => '',
    'cfgs' => '',
    'grade' => 'cstop',
  ),
  'gcom' => 
  array (
    'kid' => 'gcom',
    'model' => 'govern',
    'title' => '一般机构',
    'defmu' => '',
    'impid' => '',
    'pmadm' => '',
    'pmusr' => 'm1base,m2uedit,m2upass,m2uinfo,m2utips,m1order,m2order,m2oitem,m2oquiry,m1docs,m2idview,m2idpub',
    'mkva' => '',
    'mkvu' => '',
    'pfile' => '',
    'pmod' => '',
    'padd' => '',
    'pdel' => '',
    'pcheck' => '',
    'pextra' => '',
    'cfgs' => '',
    'grade' => 'gcom',
  ),
  'gvip' => 
  array (
    'kid' => 'gvip',
    'model' => 'govern',
    'title' => 'VIP机构',
    'defmu' => '',
    'impid' => '',
    'pmadm' => '',
    'pmusr' => 'm1base,m2uedit,m2upass,m2uinfo,m2utips,m1order,m2order,m2oitem,m2oquiry,m1docs,m2idview,m2idpub',
    'mkva' => '',
    'mkvu' => '',
    'pfile' => '',
    'pmod' => '',
    'padd' => '',
    'pdel' => '',
    'pcheck' => '',
    'pextra' => '',
    'cfgs' => '',
    'grade' => 'gvip',
  ),
  'gstop' => 
  array (
    'kid' => 'gstop',
    'model' => 'govern',
    'title' => '禁用机构',
    'defmu' => '',
    'impid' => '',
    'pmadm' => '',
    'pmusr' => 'm1base,m2uedit,m2upass,m2uinfo,m2utips,m1order,m2order,m2oitem,m2oquiry,m1docs,m2idview,m2idpub',
    'mkva' => '',
    'mkvu' => '',
    'pfile' => '',
    'pmod' => '',
    'padd' => '',
    'pdel' => '',
    'pcheck' => '',
    'pextra' => '',
    'cfgs' => '',
    'grade' => 'gstop',
  ),
  'inadm' => 
  array (
    'kid' => 'inadm',
    'model' => 'inmem',
    'title' => '超级会员',
    'defmu' => '',
    'impid' => '',
    'pmadm' => '',
    'pmusr' => 'm1base,m2uedit,m2upass,m2uinfo,m2utips,m1order,m2order,m2oitem,m2oquiry,m1docs,m2idview,m2idpub',
    'mkva' => '',
    'mkvu' => '',
    'pfile' => '',
    'pmod' => '',
    'padd' => '',
    'pdel' => '',
    'pcheck' => '',
    'pextra' => '',
    'cfgs' => '',
    'grade' => 'inadm',
  ),
  'incom' => 
  array (
    'kid' => 'incom',
    'model' => 'inmem',
    'title' => '普通会员',
    'defmu' => '',
    'impid' => '',
    'pmadm' => '',
    'pmusr' => 'm1base,m2uedit,m2upass,m2uinfo,m2utips,m1order,m2order,m2oitem,m2oquiry,m1docs,m2idview,m2idpub',
    'mkva' => '',
    'mkvu' => '',
    'pfile' => '',
    'pmod' => '',
    'padd' => '',
    'pdel' => '',
    'pcheck' => '',
    'pextra' => '',
    'cfgs' => '',
    'grade' => 'incom',
  ),
  'instop' => 
  array (
    'kid' => 'instop',
    'model' => 'inmem',
    'title' => '过期会员',
    'defmu' => '',
    'impid' => '',
    'pmadm' => '',
    'pmusr' => 'm1base,m2uedit,m2upass,m2uinfo,m2utips,m1order,m2order,m2oitem,m2oquiry,m1docs,m2idview,m2idpub',
    'mkva' => '',
    'mkvu' => '',
    'pfile' => '',
    'pmod' => '',
    'padd' => '',
    'pdel' => '',
    'pcheck' => '',
    'pextra' => '',
    'cfgs' => '',
    'grade' => 'instop',
  ),
  'zcom' => 
  array (
    'kid' => 'zcom',
    'model' => 'organize',
    'title' => '一般组织',
    'defmu' => '',
    'impid' => '',
    'pmadm' => '',
    'pmusr' => 'm1base,m2uedit,m2upass,m2uinfo,m2utips,m1order,m2order,m2oitem,m2oquiry,m1docs,m2idview,m2idpub',
    'mkva' => '',
    'mkvu' => '',
    'pfile' => '',
    'pmod' => '',
    'padd' => '',
    'pdel' => '',
    'pcheck' => '',
    'pextra' => '',
    'cfgs' => 'upsize1=200
upsizes=960000',
    'grade' => 'zcom',
  ),
  'zvip' => 
  array (
    'kid' => 'zvip',
    'model' => 'organize',
    'title' => 'VIP组织',
    'defmu' => '',
    'impid' => '',
    'pmadm' => '',
    'pmusr' => 'm1base,m2uedit,m2upass,m2uinfo,m2utips,m1order,m2order,m2oitem,m2oquiry,m1docs,m2idview,m2idpub',
    'mkva' => '',
    'mkvu' => '',
    'pfile' => '',
    'pmod' => '',
    'padd' => '',
    'pdel' => '',
    'pcheck' => '',
    'pextra' => '',
    'cfgs' => '',
    'grade' => 'zvip',
  ),
  'zstop' => 
  array (
    'kid' => 'zstop',
    'model' => 'organize',
    'title' => '过期组织',
    'defmu' => '',
    'impid' => '',
    'pmadm' => '',
    'pmusr' => 'm1base,m2uedit,m2upass,m2uinfo,m2utips,m1order,m2order,m2oitem,m2oquiry,m1docs,m2idview,m2idpub',
    'mkva' => '',
    'mkvu' => '',
    'pfile' => '',
    'pmod' => '',
    'padd' => '',
    'pdel' => '',
    'pcheck' => '',
    'pextra' => '',
    'cfgs' => '',
    'grade' => 'zstop',
  ),
  'pcom' => 
  array (
    'kid' => 'pcom',
    'model' => 'person',
    'title' => '普通个人',
    'defmu' => '',
    'impid' => '',
    'pmadm' => '',
    'pmusr' => 'm1base,m2uedit,m2upass,m2uinfo,m2utips,m1order,m2order,m2oitem,m2oquiry,m1docs,m2idview,m2idpub',
    'mkva' => '',
    'mkvu' => '',
    'pfile' => '',
    'pmod' => '',
    'padd' => '',
    'pdel' => '',
    'pcheck' => '',
    'pextra' => '',
    'cfgs' => '',
    'grade' => 'pcom',
  ),
  'pvip' => 
  array (
    'kid' => 'pvip',
    'model' => 'person',
    'title' => 'VIP个人',
    'defmu' => '',
    'impid' => '',
    'pmadm' => '',
    'pmusr' => 'm1base,m2uedit,m2upass,m2uinfo,m2utips,m1order,m2order,m2oitem,m2oquiry,m1docs,m2idview,m2idpub',
    'mkva' => '',
    'mkvu' => '',
    'pfile' => '',
    'pmod' => '',
    'padd' => '',
    'pdel' => '',
    'pcheck' => '',
    'pextra' => '',
    'cfgs' => '',
    'grade' => 'pvip',
  ),
  'pstop' => 
  array (
    'kid' => 'pstop',
    'model' => 'person',
    'title' => '过期个人',
    'defmu' => '',
    'impid' => '',
    'pmadm' => '',
    'pmusr' => 'm1base,m2uedit,m2upass,m2uinfo,m2utips,m1order,m2order,m2oitem,m2oquiry,m1docs,m2idview,m2idpub',
    'mkva' => '',
    'mkvu' => '',
    'pfile' => '',
    'pmod' => '',
    'padd' => '',
    'pdel' => '',
    'pcheck' => '',
    'pextra' => '',
    'cfgs' => '',
    'grade' => 'pstop',
  ),
);
?>