<?php
$_adfavor = array (
  'kid' => 'adfavor',
  'pid' => 'advs',
  'title' => '网址收藏',
  'enable' => '1',
  'etab' => '4',
  'deep' => '2',
  'i' => 
  array (
    'afadmin' => 
    array (
      'pid' => '0',
      'title' => '后台公用',
      'deep' => '1',
      'frame' => '0',
      'char' => 'H',
      'cfgs' => '',
    ),
    'af2012' => 
    array (
      'pid' => 'afadmin',
      'title' => '公司站群',
      'deep' => '2',
      'frame' => '0',
      'char' => 'G',
      'cfgs' => '',
    ),
    'af2016' => 
    array (
      'pid' => 'afadmin',
      'title' => '行业门户',
      'deep' => '2',
      'frame' => '0',
      'char' => 'X',
      'cfgs' => '',
    ),
    'af2020' => 
    array (
      'pid' => 'afadmin',
      'title' => '本地网站',
      'deep' => '2',
      'frame' => '0',
      'char' => 'B',
      'cfgs' => '',
    ),
    'af2024' => 
    array (
      'pid' => 'afadmin',
      'title' => '常用工具',
      'deep' => '2',
      'frame' => '0',
      'char' => 'C',
      'cfgs' => '',
    ),
    'af2032' => 
    array (
      'pid' => 'afadmin',
      'title' => '临时收藏',
      'deep' => '2',
      'frame' => '0',
      'char' => 'L',
      'cfgs' => '',
    ),
    'afauser' => 
    array (
      'pid' => '0',
      'title' => '管理员用',
      'deep' => '1',
      'frame' => '0',
      'char' => 'G',
      'cfgs' => '',
    ),
    'af4012' => 
    array (
      'pid' => 'afauser',
      'title' => '学习类',
      'deep' => '2',
      'frame' => '0',
      'char' => 'G',
      'cfgs' => '',
    ),
    'af4016' => 
    array (
      'pid' => 'afauser',
      'title' => '工作类',
      'deep' => '2',
      'frame' => '0',
      'char' => 'X',
      'cfgs' => '',
    ),
    'af4020' => 
    array (
      'pid' => 'afauser',
      'title' => '生活类',
      'deep' => '2',
      'frame' => '0',
      'char' => 'B',
      'cfgs' => '',
    ),
    'af4024' => 
    array (
      'pid' => 'afauser',
      'title' => '工具类',
      'deep' => '2',
      'frame' => '0',
      'char' => 'C',
      'cfgs' => '',
    ),
    'af4032' => 
    array (
      'pid' => 'afauser',
      'title' => '-临时-',
      'deep' => '2',
      'frame' => '0',
      'char' => 'L',
      'cfgs' => '',
    ),
    'afmemc' => 
    array (
      'pid' => '0',
      'title' => '会员中心',
      'deep' => '1',
      'frame' => '0',
      'char' => 'H',
      'cfgs' => '',
    ),
    'af6012' => 
    array (
      'pid' => 'afmemc',
      'title' => '学习类',
      'deep' => '2',
      'frame' => '0',
      'char' => 'G',
      'cfgs' => '',
    ),
    'af6016' => 
    array (
      'pid' => 'afmemc',
      'title' => '工作类',
      'deep' => '2',
      'frame' => '0',
      'char' => 'X',
      'cfgs' => '',
    ),
    'af6020' => 
    array (
      'pid' => 'afmemc',
      'title' => '生活类',
      'deep' => '2',
      'frame' => '0',
      'char' => 'B',
      'cfgs' => '',
    ),
    'af6024' => 
    array (
      'pid' => 'afmemc',
      'title' => '工具类',
      'deep' => '2',
      'frame' => '0',
      'char' => 'C',
      'cfgs' => '',
    ),
    'af6032' => 
    array (
      'pid' => 'afmemc',
      'title' => '-临时-',
      'deep' => '2',
      'frame' => '0',
      'char' => 'L',
      'cfgs' => '',
    ),
  ),
  'f' => 
  array (
    'title' => 
    array (
      'title' => '标题',
      'enable' => '1',
      'etab' => '0',
      'type' => 'input',
      'dbtype' => 'varchar',
      'dblen' => '255',
      'dbdef' => '',
      'vreg' => 'tit:2-60',
      'vtip' => '标题2-60字符',
      'vmax' => '60',
      'fmsize' => '360',
      'fmline' => '1',
      'fmtitle' => '1',
    ),
    'color' => 
    array (
      'title' => '标题颜色',
      'enable' => '1',
      'etab' => '0',
      'type' => 'input',
      'dbtype' => 'varchar',
      'dblen' => '12',
      'dbdef' => '',
      'vreg' => 'nul:str:4-7',
      'vtip' => '如:#FF00FF',
      'vmax' => '8',
      'fmsize' => '',
      'fmline' => '0',
      'fmtitle' => '0',
      'fmextra' => 'color',
      'fmexstr' => 'title',
    ),
    'ndb_repeat' => 
    array (
      'title' => '检查重复',
      'enable' => '1',
      'etab' => '0',
      'type' => 'hidden',
      'dbtype' => 'nodb',
      'dblen' => '255',
      'dbdef' => '',
      'vreg' => '',
      'vtip' => '',
      'vmax' => '0',
      'fmsize' => '',
      'fmline' => '0',
      'fmtitle' => '0',
      'fmextra' => 'repeat',
    ),
    'detail' => 
    array (
      'title' => '内容',
      'enable' => '1',
      'etab' => '0',
      'type' => 'text',
      'dbtype' => 'text',
      'dblen' => '0',
      'dbdef' => '',
      'vreg' => '',
      'vtip' => '',
      'vmax' => '24012',
      'fmsize' => '480x8',
      'fmline' => '1',
      'fmtitle' => '1',
      'fmextra' => 'text',
      'fmexstr' => '',
    ),
    'mpic' => 
    array (
      'title' => '缩略图',
      'enable' => '1',
      'etab' => '0',
      'type' => 'file',
      'dbtype' => 'varchar',
      'dblen' => '255',
      'dbdef' => '',
      'vreg' => 'nul:fix:image',
      'vtip' => 'gif/jpg/jpeg/png格式.',
      'vmax' => '255',
      'fmsize' => '',
      'fmline' => '1',
      'fmtitle' => '1',
    ),
    'url' => 
    array (
      'title' => 'Url地址',
      'enable' => '1',
      'etab' => '0',
      'type' => 'input',
      'dbtype' => 'varchar',
      'dblen' => '255',
      'dbdef' => '',
      'vreg' => 'nul:fix:uri',
      'vtip' => 'http://开头',
      'vmax' => '255',
      'fmsize' => '480',
      'fmline' => '1',
      'fmtitle' => '1',
    ),
    'click' => 
    array (
      'title' => '点击次数',
      'enable' => '1',
      'etab' => '0',
      'type' => 'input',
      'dbtype' => 'int',
      'dblen' => '10',
      'dbdef' => '0',
      'vreg' => 'n+i',
      'vtip' => '如:888',
      'vmax' => '8',
      'fmsize' => '',
      'fmline' => '1',
      'fmtitle' => '1',
    ),
  ),
);
?>