<?php
$_adpic = array (
  'kid' => 'adpic',
  'pid' => 'advs',
  'title' => '图片连接',
  'enable' => '1',
  'etab' => '2',
  'deep' => '2',
  'i' => 
  array (
    'aphom' => 
    array (
      'pid' => '0',
      'title' => '首页广告',
      'deep' => '1',
      'frame' => '0',
      'char' => 'S',
      'cfgs' => '',
    ),
    'a2012' => 
    array (
      'pid' => 'aphom',
      'title' => '[顶]620x60',
      'deep' => '2',
      'frame' => '0',
      'char' => '[',
      'cfgs' => '<a href=\'{url}\'><img src=\'{mpic}\' width=\'620\' height=\'60\' name=\'{title}\' alt=\'{title}\' /></a>',
    ),
    'a2014' => 
    array (
      'pid' => 'aphom',
      'title' => '[上]850x80',
      'deep' => '2',
      'frame' => '0',
      'char' => '[',
      'cfgs' => '<a href=\'{url}\'><img src=\'{mpic}\' width=\'800\' height=\'80\' name=\'{title}\' alt=\'{title}\' /></a>',
    ),
    'apinn' => 
    array (
      'pid' => '0',
      'title' => '通用内页',
      'deep' => '1',
      'frame' => '0',
      'char' => 'N',
      'cfgs' => '',
    ),
    'a2016' => 
    array (
      'pid' => 'apinn',
      'title' => '推荐资源[侧]',
      'deep' => '2',
      'frame' => '0',
      'char' => 'T',
      'cfgs' => '',
    ),
    'a2018' => 
    array (
      'pid' => 'apinn',
      'title' => '广告[侧边]A',
      'deep' => '2',
      'frame' => '0',
      'char' => 'G',
      'cfgs' => '',
    ),
    'a2020' => 
    array (
      'pid' => 'apinn',
      'title' => '广告[侧边]B',
      'deep' => '2',
      'frame' => '0',
      'char' => 'G',
      'cfgs' => '',
    ),
    'apdel' => 
    array (
      'pid' => '0',
      'title' => '[回收站]',
      'deep' => '1',
      'frame' => '0',
      'char' => 'H',
      'cfgs' => '',
    ),
  ),
  'f' => 
  array (
    'title' => 
    array (
      'title' => '标题',
      'enable' => '1',
      'etab' => '0',
      'type' => 'input',
      'dbtype' => 'varchar',
      'dblen' => '255',
      'dbdef' => '',
      'vreg' => 'tit:2-60',
      'vtip' => '标题2-60字符',
      'vmax' => '60',
      'fmsize' => '360',
      'fmline' => '1',
      'fmtitle' => '1',
    ),
    'color' => 
    array (
      'title' => '标题颜色',
      'enable' => '1',
      'etab' => '0',
      'type' => 'input',
      'dbtype' => 'varchar',
      'dblen' => '12',
      'dbdef' => '',
      'vreg' => 'nul:str:4-7',
      'vtip' => '如:#FF00FF',
      'vmax' => '8',
      'fmsize' => '',
      'fmline' => '0',
      'fmtitle' => '0',
      'fmextra' => 'color',
      'fmexstr' => 'title',
    ),
    'ndb_repeat' => 
    array (
      'title' => '检查重复',
      'enable' => '1',
      'etab' => '0',
      'type' => 'hidden',
      'dbtype' => 'nodb',
      'dblen' => '255',
      'dbdef' => '',
      'vreg' => '',
      'vtip' => '',
      'vmax' => '0',
      'fmsize' => '',
      'fmline' => '0',
      'fmtitle' => '0',
      'fmextra' => 'repeat',
    ),
    'mpic' => 
    array (
      'title' => '缩略图',
      'enable' => '1',
      'etab' => '0',
      'type' => 'file',
      'dbtype' => 'varchar',
      'dblen' => '255',
      'dbdef' => '',
      'vreg' => 'nul:fix:image',
      'vtip' => 'gif/jpg/jpeg/png格式.',
      'vmax' => '255',
      'fmsize' => '',
      'fmline' => '1',
      'fmtitle' => '1',
    ),
    'url' => 
    array (
      'title' => 'Url地址',
      'enable' => '1',
      'etab' => '0',
      'type' => 'input',
      'dbtype' => 'varchar',
      'dblen' => '255',
      'dbdef' => '',
      'vreg' => 'nul:fix:uri',
      'vtip' => 'http://开头',
      'vmax' => '255',
      'fmsize' => '480',
      'fmline' => '1',
      'fmtitle' => '1',
    ),
    'click' => 
    array (
      'title' => '点击次数',
      'enable' => '1',
      'etab' => '0',
      'type' => 'input',
      'dbtype' => 'int',
      'dblen' => '10',
      'dbdef' => '0',
      'vreg' => 'n+i',
      'vtip' => '如:888',
      'vmax' => '8',
      'fmsize' => '',
      'fmline' => '1',
      'fmtitle' => '1',
    ),
  ),
);
?>