<?php
$_brand = array (
  'kid' => 'brand',
  'pid' => 'types',
  'title' => '品牌',
  'enable' => '1',
  'etab' => '1',
  'deep' => '1',
  'cfgs' => 'exdoc=1',
  'f' => 
  array (
    'world' => 
    array (
      'kid' => 'world',
      'model' => 'brand',
      'title' => '国别',
      'top' => '120',
      'enable' => '1',
      'etab' => '0',
      'type' => 'input',
      'dbtype' => 'varchar',
      'dblen' => '12',
      'dbdef' => '',
      'vreg' => '',
      'vtip' => '',
      'vmax' => '255',
      'fmsize' => '',
      'fmline' => '1',
      'fmtitle' => '0',
      'fmextra' => 'winpop',
      'fmexstr' => 'world',
      'cfgs' => '',
      'note' => '',
      'aip' => '',
      'atime' => '0',
      'auser' => '',
      'eip' => '',
      'etime' => '0',
      'euser' => '',
    ),
    'bpic' => 
    array (
      'kid' => 'bpic',
      'model' => 'brand',
      'title' => 'logo',
      'top' => '124',
      'enable' => '1',
      'etab' => '0',
      'type' => 'file',
      'dbtype' => 'varchar',
      'dblen' => '255',
      'dbdef' => '',
      'vreg' => 'nul:fix:image',
      'vtip' => 'gif/jpg/jpeg/png格式.',
      'vmax' => '255',
      'fmsize' => '320',
      'fmline' => '1',
      'fmtitle' => '0',
      'fmextra' => '',
      'fmexstr' => '',
      'cfgs' => '',
      'note' => '',
      'aip' => '',
      'atime' => '0',
      'auser' => '',
      'eip' => '',
      'etime' => '0',
      'euser' => '',
    ),
    'bweb' => 
    array (
      'kid' => 'bweb',
      'model' => 'brand',
      'title' => '网址',
      'top' => '136',
      'enable' => '1',
      'etab' => '0',
      'type' => 'input',
      'dbtype' => 'varchar',
      'dblen' => '255',
      'dbdef' => '',
      'vreg' => 'nul:fix:uri',
      'vtip' => 'http://开头',
      'vmax' => '255',
      'fmsize' => '420',
      'fmline' => '1',
      'fmtitle' => '0',
      'fmextra' => '',
      'fmexstr' => '',
      'cfgs' => '',
      'note' => '',
      'aip' => '',
      'atime' => '0',
      'auser' => '',
      'eip' => '',
      'etime' => '0',
      'euser' => '',
    ),
    'detail' => 
    array (
      'kid' => 'detail',
      'model' => 'brand',
      'title' => '内容',
      'top' => '888',
      'enable' => '1',
      'etab' => '0',
      'type' => 'text',
      'dbtype' => 'text',
      'dblen' => '0',
      'dbdef' => '',
      'vreg' => 'nul:str:10+',
      'vtip' => '内容10字符以上',
      'vmax' => '0',
      'fmsize' => '480x240',
      'fmline' => '1',
      'fmtitle' => '0',
      'fmextra' => 'editor',
      'fmexstr' => '',
      'cfgs' => '',
      'note' => '',
      'aip' => '',
      'atime' => '0',
      'auser' => '',
      'eip' => '',
      'etime' => '0',
      'euser' => '',
    ),
  ),
  'i' => 
  array (
    'gree' => 
    array (
      'kid' => 'gree',
      'pid' => '0',
      'title' => '格力',
      'deep' => '1',
      'frame' => '0',
      'char' => 'G',
      'cfgs' => '',
    ),
    'haier' => 
    array (
      'kid' => 'haier',
      'pid' => '0',
      'title' => '海尔',
      'deep' => '1',
      'frame' => '0',
      'char' => 'H',
      'cfgs' => '',
    ),
    'midea' => 
    array (
      'kid' => 'midea',
      'pid' => '0',
      'title' => '美的',
      'deep' => '1',
      'frame' => '0',
      'char' => 'M',
      'cfgs' => '',
    ),
    'kelon' => 
    array (
      'kid' => 'kelon',
      'pid' => '0',
      'title' => '科龙',
      'deep' => '1',
      'frame' => '0',
      'char' => 'K',
      'cfgs' => '',
    ),
    'tcl' => 
    array (
      'kid' => 'tcl',
      'pid' => '0',
      'title' => 'TCL',
      'deep' => '1',
      'frame' => '0',
      'char' => 'T',
      'cfgs' => '',
    ),
    'konka' => 
    array (
      'kid' => 'konka',
      'pid' => '0',
      'title' => '康佳',
      'deep' => '1',
      'frame' => '0',
      'char' => 'K',
      'cfgs' => '',
    ),
    'supor' => 
    array (
      'kid' => 'supor',
      'pid' => '0',
      'title' => '苏泊尔',
      'deep' => '1',
      'frame' => '0',
      'char' => 'S',
      'cfgs' => '',
    ),
    'chong' => 
    array (
      'kid' => 'chong',
      'pid' => '0',
      'title' => '长虹',
      'deep' => '1',
      'frame' => '0',
      'char' => 'C',
      'cfgs' => '',
    ),
    'trchi' => 
    array (
      'kid' => 'trchi',
      'pid' => '0',
      'title' => '传祺',
      'deep' => '1',
      'frame' => '0',
      'char' => 'C',
      'cfgs' => '',
    ),
    'dfpv' => 
    array (
      'kid' => 'dfpv',
      'pid' => '0',
      'title' => '东风风神',
      'deep' => '1',
      'frame' => '0',
      'char' => 'D',
      'cfgs' => '',
    ),
    'hongqi' => 
    array (
      'kid' => 'hongqi',
      'pid' => '0',
      'title' => '红旗',
      'deep' => '1',
      'frame' => '0',
      'char' => 'H',
      'cfgs' => '',
    ),
    'roewe' => 
    array (
      'kid' => 'roewe',
      'pid' => '0',
      'title' => '荣威',
      'deep' => '1',
      'frame' => '0',
      'char' => 'R',
      'cfgs' => '',
    ),
    'ymj' => 
    array (
      'kid' => 'ymj',
      'pid' => '0',
      'title' => '郁美净',
      'deep' => '1',
      'frame' => '0',
      'char' => 'Y',
      'cfgs' => '',
    ),
    'dabao' => 
    array (
      'kid' => 'dabao',
      'pid' => '0',
      'title' => '大宝',
      'deep' => '1',
      'frame' => '0',
      'char' => 'D',
      'cfgs' => '',
    ),
    'huawei' => 
    array (
      'kid' => 'huawei',
      'pid' => '0',
      'title' => '华为',
      'deep' => '1',
      'frame' => '0',
      'char' => 'H',
      'cfgs' => '',
    ),
    'zhongxing' => 
    array (
      'kid' => 'zhongxing',
      'pid' => '0',
      'title' => '中兴',
      'deep' => '1',
      'frame' => '0',
      'char' => 'Z',
      'cfgs' => '',
    ),
    'xiaomi' => 
    array (
      'kid' => 'xiaomi',
      'pid' => '0',
      'title' => '小米',
      'deep' => '1',
      'frame' => '0',
      'char' => 'X',
      'cfgs' => '',
    ),
    'aimo' => 
    array (
      'kid' => 'aimo',
      'pid' => '0',
      'title' => '爱慕',
      'deep' => '1',
      'frame' => '0',
      'char' => 'A',
      'cfgs' => '',
    ),
    'bailian' => 
    array (
      'kid' => 'bailian',
      'pid' => '0',
      'title' => '百利安',
      'deep' => '1',
      'frame' => '0',
      'char' => 'B',
      'cfgs' => '',
    ),
  ),
);
?>