<?php
$_cocar = array (
  'kid' => 'cocar',
  'pid' => 'coms',
  'title' => '购物车',
  'enable' => '1',
  'etab' => '0',
  'deep' => '1',
  'pmod' => 'cargo',
  'f' => 
  array (
    'ordprice' => 
    array (
      'kid' => 'ordprice',
      'title' => '价格',
      'etab' => '0',
      'type' => 'input',
      'dbtype' => 'float',
      'dblen' => '8',
      'dbdef' => '0',
      'vreg' => '',
      'vtip' => '',
      'vmax' => '8',
      'fmsize' => '',
      'fmline' => '1',
      'fmtitle' => '0',
      'fmextra' => '',
      'fmexstr' => '',
      'cfgs' => '',
    ),
    'ordcnt' => 
    array (
      'kid' => 'ordcnt',
      'title' => '数量',
      'etab' => '0',
      'type' => 'input',
      'dbtype' => 'int',
      'dblen' => '8',
      'dbdef' => '0',
      'vreg' => '',
      'vtip' => '',
      'vmax' => '8',
      'fmsize' => '',
      'fmline' => '1',
      'fmtitle' => '0',
      'fmextra' => '',
      'fmexstr' => '',
      'cfgs' => '',
    ),
    'ordweight' => 
    array (
      'kid' => 'ordweight',
      'title' => '重量',
      'etab' => '0',
      'type' => 'input',
      'dbtype' => 'float',
      'dblen' => '8',
      'dbdef' => '0',
      'vreg' => '',
      'vtip' => '',
      'vmax' => '8',
      'fmsize' => '',
      'fmline' => '1',
      'fmtitle' => '0',
      'fmextra' => '',
      'fmexstr' => '',
      'cfgs' => '',
    ),
    'title' => 
    array (
      'kid' => 'title',
      'title' => '备注',
      'etab' => '0',
      'type' => 'input',
      'dbtype' => 'varchar',
      'dblen' => '255',
      'dbdef' => '',
      'vreg' => '',
      'vtip' => '标题2-60字符',
      'vmax' => '255',
      'fmsize' => '360',
      'fmline' => '1',
      'fmtitle' => '1',
      'fmextra' => '',
      'fmexstr' => '',
      'cfgs' => '',
    ),
    'detail' => 
    array (
      'kid' => 'detail',
      'title' => '参数',
      'etab' => '0',
      'type' => 'text',
      'dbtype' => 'text',
      'dblen' => '0',
      'dbdef' => '',
      'vreg' => 'nul:',
      'vtip' => '内容10字符以上',
      'vmax' => '255',
      'fmsize' => '360',
      'fmline' => '1',
      'fmtitle' => '1',
      'fmextra' => '',
      'fmexstr' => '',
      'cfgs' => '',
    ),
  ),
);
?>