<?php
$_demo = array (
  'kid' => 'demo',
  'pid' => 'docs',
  'title' => '样例文档',
  'enable' => '1',
  'etab' => '1',
  'deep' => '2',
  'f' => 
  array (
    'title' => 
    array (
      'title' => '标题',
      'enable' => '1',
      'etab' => '0',
      'type' => 'input',
      'dbtype' => 'varchar',
      'dblen' => '255',
      'dbdef' => '',
      'vreg' => 'tit:2-60',
      'vtip' => '标题2-60字符',
      'vmax' => '60',
      'fmsize' => '480',
      'fmline' => '1',
      'fmtitle' => '1',
    ),
    'color' => 
    array (
      'title' => '标题颜色',
      'enable' => '1',
      'etab' => '0',
      'type' => 'hidden',
      'dbtype' => 'varchar',
      'dblen' => '255',
      'dbdef' => '',
      'vreg' => 'nul:',
      'vtip' => '如:#FF00FF',
      'vmax' => '0',
      'fmsize' => '',
      'fmline' => '0',
      'fmtitle' => '0',
      'fmextra' => 'color',
      'fmexstr' => 'title',
    ),
    'ndb_repeat' => 
    array (
      'title' => '检查重复',
      'enable' => '1',
      'etab' => '0',
      'type' => 'repeat',
      'dbtype' => 'nodb',
      'dblen' => '0',
      'dbdef' => '',
      'vreg' => '',
      'vtip' => '',
      'vmax' => '0',
      'fmsize' => '',
      'fmline' => '0',
      'fmtitle' => '0',
      'cfgs' => 'demo,title',
      'fmextra' => 'repeat',
    ),
    'detail' => 
    array (
      'title' => '内容',
      'enable' => '1',
      'etab' => '1',
      'type' => 'text',
      'dbtype' => 'mediumtext',
      'dblen' => '0',
      'dbdef' => '',
      'vreg' => 'nul:str:10+',
      'vtip' => '内容10字符以上',
      'vmax' => '0',
      'fmsize' => '550x240',
      'fmline' => '1',
      'fmtitle' => '1',
      'fmextra' => 'editor',
      'fmexstr' => 'full,exbar',
    ),
    'mpic' => 
    array (
      'title' => '缩略图',
      'enable' => '1',
      'etab' => '0',
      'type' => 'file',
      'dbtype' => 'varchar',
      'dblen' => '255',
      'dbdef' => '',
      'vreg' => 'nul:fix:image',
      'vtip' => 'gif/jpg/jpeg/png格式.',
      'vmax' => '255',
      'fmsize' => '320',
      'fmline' => '1',
      'fmtitle' => '1',
    ),
    'click' => 
    array (
      'title' => '点击次数',
      'enable' => '1',
      'etab' => '0',
      'type' => 'input',
      'dbtype' => 'int',
      'dblen' => '10',
      'dbdef' => '0',
      'vreg' => 'n+i',
      'vtip' => '如:888',
      'vmax' => '12',
      'fmsize' => '60',
      'fmline' => '1',
      'fmtitle' => '0',
    ),
    'top' => 
    array (
      'title' => '显示顺序',
      'enable' => '1',
      'etab' => '0',
      'type' => 'input',
      'dbtype' => 'int',
      'dblen' => '10',
      'dbdef' => '888',
      'vreg' => 'n-i',
      'vtip' => '如:888',
      'vmax' => '12',
      'fmsize' => '60',
      'fmline' => '0',
      'fmtitle' => '1',
    ),
    'dstart' => 
    array (
      'title' => '开始时间',
      'enable' => '1',
      'etab' => '1',
      'type' => 'input',
      'dbtype' => 'int',
      'dblen' => '11',
      'dbdef' => '',
      'vreg' => 'nul:str:2-255',
      'vtip' => '',
      'vmax' => '255',
      'fmsize' => '',
      'fmline' => '1',
      'fmtitle' => '0',
      'fmextra' => 'datetm',
    ),
    'dend' => 
    array (
      'title' => '结束时间',
      'enable' => '1',
      'etab' => '0',
      'type' => 'input',
      'dbtype' => 'int',
      'dblen' => '11',
      'dbdef' => '',
      'vreg' => 'nul:str:2-255',
      'vtip' => '',
      'vmax' => '255',
      'fmsize' => '150',
      'fmline' => '0',
      'fmtitle' => '1',
      'fmextra' => 'datetm',
      'fmexstr' => 'Y-m-d H:i:s',
    ),
    'ndb_extra' => 
    array (
      'title' => '扩展设置',
      'enable' => '1',
      'etab' => '0',
      'type' => 'parts',
      'dbtype' => 'nodb',
      'dblen' => '255',
      'dbdef' => '',
      'vreg' => '',
      'vtip' => '',
      'vmax' => '0',
      'fmsize' => '',
      'fmline' => '1',
      'fmtitle' => '0',
    ),
    'jump' => 
    array (
      'title' => '跳转地址',
      'enable' => '1',
      'etab' => '0',
      'type' => 'input',
      'dbtype' => 'varchar',
      'dblen' => '255',
      'dbdef' => '',
      'vreg' => 'nul:fix:uri',
      'vtip' => 'http://开头',
      'vmax' => '255',
      'fmsize' => '360',
      'fmline' => '1',
      'fmtitle' => '1',
    ),
    'author' => 
    array (
      'title' => '作者',
      'enable' => '1',
      'etab' => '1',
      'type' => 'input',
      'dbtype' => 'varchar',
      'dblen' => '255',
      'dbdef' => '',
      'vreg' => '',
      'vtip' => '',
      'vmax' => '255',
      'fmsize' => '',
      'fmline' => '1',
      'fmtitle' => '1',
    ),
    'seo_key' => 
    array (
      'title' => '关键字',
      'enable' => '1',
      'etab' => '1',
      'type' => 'input',
      'dbtype' => 'varchar',
      'dblen' => '255',
      'dbdef' => '',
      'vreg' => '',
      'vtip' => '',
      'vmax' => '255',
      'fmsize' => '',
      'fmline' => '1',
      'fmtitle' => '1',
    ),
    'seo_des' => 
    array (
      'title' => '描述',
      'enable' => '1',
      'etab' => '1',
      'type' => 'input',
      'dbtype' => 'varchar',
      'dblen' => '255',
      'dbdef' => '',
      'vreg' => '',
      'vtip' => '',
      'vmax' => '255',
      'fmsize' => '',
      'fmline' => '0',
      'fmtitle' => '1',
    ),
    'seo_tag' => 
    array (
      'title' => '标签',
      'enable' => '1',
      'etab' => '1',
      'type' => 'input',
      'dbtype' => 'varchar',
      'dblen' => '255',
      'dbdef' => '',
      'vreg' => '',
      'vtip' => '',
      'vmax' => '255',
      'fmsize' => '',
      'fmline' => '0',
      'fmtitle' => '1',
    ),
    'ndb_demo' => 
    array (
      'title' => '演示字段',
      'enable' => '1',
      'etab' => '0',
      'type' => 'parts',
      'dbtype' => 'nodb',
      'dblen' => '255',
      'dbdef' => '',
      'vreg' => '',
      'vtip' => '',
      'vmax' => '0',
      'fmsize' => '',
      'fmline' => '1',
      'fmtitle' => '0',
    ),
    'mname' => 
    array (
      'title' => '会员名称',
      'enable' => '1',
      'etab' => '0',
      'type' => 'input',
      'dbtype' => 'varchar',
      'dblen' => '24',
      'dbdef' => 'tester',
      'vreg' => 'str:2-24',
      'vtip' => '',
      'vmax' => '24',
      'fmsize' => '',
      'fmline' => '1',
      'fmtitle' => '0',
    ),
    'demo_pass' => 
    array (
      'title' => '密码',
      'enable' => '1',
      'etab' => '0',
      'type' => 'passwd',
      'dbtype' => 'varchar',
      'dblen' => '255',
      'dbdef' => '',
      'vreg' => 'nul:str:6-24',
      'vtip' => '',
      'vmax' => '24',
      'fmsize' => '',
      'fmline' => '0',
      'fmtitle' => '0',
    ),
    'mtitle' => 
    array (
      'title' => '*联系人',
      'enable' => '1',
      'etab' => '0',
      'type' => 'input',
      'dbtype' => 'varchar',
      'dblen' => '24',
      'dbdef' => '',
      'vreg' => 'nul:tit:2-24',
      'vtip' => '',
      'vmax' => '24',
      'fmsize' => '',
      'fmline' => '1',
      'fmtitle' => '0',
    ),
    'mfrom' => 
    array (
      'title' => '选择省份',
      'enable' => '1',
      'etab' => '0',
      'type' => 'select',
      'dbtype' => 'varchar',
      'dblen' => '12',
      'dbdef' => 'hn',
      'vreg' => 'str:2-12',
      'vtip' => '至少选两个',
      'vmax' => '12',
      'fmsize' => '',
      'fmline' => '0',
      'fmtitle' => '1',
      'cfgs' => 'sc=四川
gd=广东
hn=湖南
gx=广西
jx=江西',
    ),
    'mfron' => 
    array (
      'title' => '流浪省份',
      'enable' => '1',
      'etab' => '0',
      'type' => 'cbox',
      'dbtype' => 'varchar',
      'dblen' => '255',
      'dbdef' => 'gd,gx',
      'vreg' => 'str:2-255',
      'vtip' => '',
      'vmax' => '255',
      'fmsize' => '',
      'fmline' => '1',
      'fmtitle' => '0',
      'cfgs' => 'sc=四川
gd=广东
hn=湖南
gx=广西
jx=江西',
    ),
    'morg' => 
    array (
      'title' => '地区单选',
      'enable' => '1',
      'etab' => '0',
      'type' => 'input',
      'dbtype' => 'varchar',
      'dblen' => '12',
      'dbdef' => 'c0735',
      'vreg' => 'str:2-255',
      'vtip' => '',
      'vmax' => '255',
      'fmsize' => '60x1',
      'fmline' => '1',
      'fmtitle' => '0',
      'cfgs' => 'pid:"cnhn",w:320',
      'fmextra' => 'winpop',
      'fmexstr' => 'china',
    ),
    'mwork' => 
    array (
      'title' => '工作地',
      'enable' => '1',
      'etab' => '0',
      'type' => 'input',
      'dbtype' => 'varchar',
      'dblen' => '12',
      'dbdef' => '',
      'vreg' => 'nul:str:2-255',
      'vtip' => '',
      'vmax' => '255',
      'fmsize' => '240x3',
      'fmline' => '1',
      'fmtitle' => '0',
      'fmextra' => 'winpop',
      'fmexstr' => 'china',
    ),
    'tphot' => 
    array (
      'title' => '信息推荐',
      'enable' => '1',
      'etab' => '0',
      'type' => 'input',
      'dbtype' => 'varchar',
      'dblen' => '12',
      'dbdef' => '',
      'vreg' => 'nul:str:2-255',
      'vtip' => '',
      'vmax' => '255',
      'fmsize' => '180x1',
      'fmline' => '1',
      'fmtitle' => '0',
      'fmextra' => 'winpop',
      'fmexstr' => 'hinfo',
    ),
    'tpfields' => 
    array (
      'title' => '行业类别',
      'enable' => '1',
      'etab' => '0',
      'type' => 'input',
      'dbtype' => 'varchar',
      'dblen' => '255',
      'dbdef' => 'qita',
      'vreg' => 'str:2-255',
      'vtip' => '',
      'vmax' => '255',
      'fmsize' => '360x3',
      'fmline' => '1',
      'fmtitle' => '0',
      'fmextra' => 'winpop',
      'fmexstr' => 'ftype',
    ),
    'wdreg' => 
    array (
      'title' => '世界地区',
      'enable' => '1',
      'etab' => '0',
      'type' => 'input',
      'dbtype' => 'varchar',
      'dblen' => '12',
      'dbdef' => '',
      'vreg' => '',
      'vtip' => '',
      'vmax' => '255',
      'fmsize' => '240x3',
      'fmline' => '1',
      'fmtitle' => '0',
      'fmextra' => 'winpop',
      'fmexstr' => 'world',
    ),
    'mche' => 
    array (
      'title' => '汽车品牌',
      'enable' => '1',
      'etab' => '0',
      'type' => 'input',
      'dbtype' => 'varchar',
      'dblen' => '255',
      'dbdef' => '',
      'vreg' => '',
      'vtip' => '',
      'vmax' => '255',
      'fmsize' => '240x4',
      'fmline' => '1',
      'fmtitle' => '0',
      'fmextra' => 'winpop',
      'fmexstr' => 'auto',
    ),
    'mtel' => 
    array (
      'title' => '电话',
      'enable' => '1',
      'etab' => '0',
      'type' => 'input',
      'dbtype' => 'varchar',
      'dblen' => '24',
      'dbdef' => '',
      'vreg' => '',
      'vtip' => '',
      'vmax' => '24',
      'fmsize' => '',
      'fmline' => '1',
      'fmtitle' => '0',
    ),
    'map' => 
    array (
      'title' => '地图',
      'enable' => '1',
      'etab' => '0',
      'type' => 'input',
      'dbtype' => 'varchar',
      'dblen' => '48',
      'dbdef' => '',
      'vreg' => '',
      'vtip' => '',
      'vmax' => '48',
      'fmsize' => '240',
      'fmline' => '0',
      'fmtitle' => '0',
      'fmextra' => 'map',
    ),
    'miuid' => 
    array (
      'title' => '聊天号',
      'enable' => '1',
      'etab' => '0',
      'type' => 'input',
      'dbtype' => 'varchar',
      'dblen' => '120',
      'dbdef' => '',
      'vreg' => '',
      'vtip' => '',
      'vmax' => '120',
      'fmsize' => '',
      'fmline' => '1',
      'fmtitle' => '0',
    ),
    'memail' => 
    array (
      'title' => '邮件地址',
      'enable' => '1',
      'etab' => '0',
      'type' => 'input',
      'dbtype' => 'varchar',
      'dblen' => '255',
      'dbdef' => 'a_b@09-cms.cn',
      'vreg' => 'fix:email',
      'vtip' => '',
      'vmax' => '255',
      'fmsize' => '180',
      'fmline' => '0',
      'fmtitle' => '0',
    ),
    'mweb' => 
    array (
      'title' => '网址',
      'enable' => '1',
      'etab' => '0',
      'type' => 'input',
      'dbtype' => 'varchar',
      'dblen' => '255',
      'dbdef' => 'http://192.168.1.11/',
      'vreg' => 'fix:uri',
      'vtip' => '',
      'vmax' => '255',
      'fmsize' => '180',
      'fmline' => '1',
      'fmtitle' => '0',
    ),
    'maddr' => 
    array (
      'title' => '地址',
      'enable' => '1',
      'etab' => '0',
      'type' => 'input',
      'dbtype' => 'varchar',
      'dblen' => '120',
      'dbdef' => '',
      'vreg' => '',
      'vtip' => '',
      'vmax' => '120',
      'fmsize' => '150',
      'fmline' => '0',
      'fmtitle' => '0',
    ),
    'company' => 
    array (
      'title' => '公司名称',
      'enable' => '1',
      'etab' => '0',
      'type' => 'input',
      'dbtype' => 'varchar',
      'dblen' => '96',
      'dbdef' => 'dgnet',
      'vreg' => 'str:2-24',
      'vtip' => '',
      'vmax' => '24',
      'fmsize' => '420',
      'fmline' => '1',
      'fmtitle' => '0',
    ),
    'ndb_rel' => 
    array (
      'title' => '相关信息',
      'enable' => '1',
      'etab' => '0',
      'type' => 'parts',
      'dbtype' => 'nodb',
      'dblen' => '0',
      'dbdef' => '',
      'vreg' => '',
      'vtip' => '',
      'vmax' => '0',
      'fmsize' => 'cargo.12',
      'fmline' => '1',
      'fmtitle' => '1',
    ),
    'rel_user' => 
    array (
      'title' => '相关用户',
      'enable' => '1',
      'etab' => '1',
      'type' => 'text',
      'dbtype' => 'text',
      'dblen' => '0',
      'dbdef' => '',
      'vreg' => 'nul:',
      'vtip' => '',
      'vmax' => '0',
      'fmsize' => 'company.12',
      'fmline' => '1',
      'fmtitle' => '1',
      'fmextra' => 'pick',
    ),
    'rel_doc' => 
    array (
      'title' => '相关信息',
      'enable' => '1',
      'etab' => '1',
      'type' => 'text',
      'dbtype' => 'text',
      'dblen' => '0',
      'dbdef' => '',
      'vreg' => '',
      'vtip' => '',
      'vmax' => '0',
      'fmsize' => 'cargo.12',
      'fmline' => '1',
      'fmtitle' => '1',
      'fmextra' => 'pick',
    ),
    'rel_para' => 
    array (
      'title' => '相关参数',
      'enable' => '1',
      'etab' => '0',
      'type' => 'text',
      'dbtype' => 'text',
      'dblen' => '0',
      'dbdef' => '',
      'vreg' => '',
      'vtip' => '',
      'vmax' => '0',
      'fmsize' => '480x3',
      'fmline' => '1',
      'fmtitle' => '1',
    ),
    'rel_pic' => 
    array (
      'title' => '相关图片',
      'enable' => '1',
      'etab' => '1',
      'type' => 'text',
      'dbtype' => 'text',
      'dblen' => '0',
      'dbdef' => '',
      'vreg' => 'nul:',
      'vtip' => '',
      'vmax' => '0',
      'fmsize' => '',
      'fmline' => '1',
      'fmtitle' => '1',
      'cfgs' => 'tout=外观图
tin=内饰
telse=配件',
      'fmextra' => 'pics',
    ),
  ),
  'i' => 
  array (
    'd1016' => 
    array (
      'pid' => '0',
      'title' => '系统文档',
      'deep' => '1',
      'frame' => '0',
      'char' => 'X',
      'cfgs' => '',
    ),
    'd1012' => 
    array (
      'pid' => '0',
      'title' => '英语美文',
      'deep' => '1',
      'frame' => '0',
      'char' => 'Y',
      'cfgs' => '',
    ),
    'd2012' => 
    array (
      'pid' => 'd1012',
      'title' => '英语美文1',
      'deep' => '2',
      'frame' => '0',
      'char' => 'Z',
      'cfgs' => '',
    ),
    'd2014' => 
    array (
      'pid' => 'd1012',
      'title' => '英语美文2',
      'deep' => '2',
      'frame' => '0',
      'char' => 'Z',
      'cfgs' => '',
    ),
    'd1014' => 
    array (
      'pid' => '0',
      'title' => '幽默搞笑',
      'deep' => '1',
      'frame' => '0',
      'char' => 'Y',
      'cfgs' => '',
    ),
    'd1018' => 
    array (
      'pid' => '0',
      'title' => '编辑说明',
      'deep' => '1',
      'frame' => '0',
      'char' => 'B',
      'cfgs' => '',
    ),
    'dtest' => 
    array (
      'pid' => '0',
      'title' => '测试栏目',
      'deep' => '1',
      'frame' => '0',
      'char' => 'C',
      'cfgs' => '',
    ),
    'dsub1' => 
    array (
      'pid' => 'dtest',
      'title' => '测试子类3',
      'deep' => '2',
      'frame' => '0',
      'char' => 'Z',
      'cfgs' => '',
    ),
    'd2018' => 
    array (
      'pid' => 'dtest',
      'title' => '测试子类4',
      'deep' => '2',
      'frame' => '0',
      'char' => 'Z',
      'cfgs' => '',
    ),
  ),
);
?>