<?php
$_indep = array (
  'kid' => 'indep',
  'pid' => 'types',
  'title' => '部门',
  'enable' => '1',
  'etab' => '1',
  'deep' => '1',
  'cfgs' => 'exdoc=1',
  'f' => 
  array (
    'tel' => 
    array (
      'kid' => 'tel',
      'model' => 'indep',
      'title' => '电话',
      'top' => '120',
      'enable' => '1',
      'etab' => '0',
      'type' => 'input',
      'dbtype' => 'varchar',
      'dblen' => '15',
      'dbdef' => '',
      'vreg' => 'nul:fix:tel',
      'vtip' => '',
      'vmax' => '24',
      'fmsize' => '',
      'fmline' => '1',
      'fmtitle' => '0',
      'fmextra' => '',
      'fmexstr' => '',
      'cfgs' => '',
      'note' => '',
      'aip' => '',
      'atime' => '0',
      'auser' => '',
      'eip' => '',
      'etime' => '0',
      'euser' => '',
    ),
    'detail' => 
    array (
      'kid' => 'detail',
      'model' => 'indep',
      'title' => '简介',
      'top' => '888',
      'enable' => '1',
      'etab' => '0',
      'type' => 'text',
      'dbtype' => 'text',
      'dblen' => '0',
      'dbdef' => '',
      'vreg' => 'nul:',
      'vtip' => '',
      'vmax' => '0',
      'fmsize' => '360x6',
      'fmline' => '1',
      'fmtitle' => '0',
      'fmextra' => '',
      'fmexstr' => '',
      'cfgs' => '',
      'note' => '',
      'aip' => '',
      'atime' => '0',
      'auser' => '',
      'eip' => '',
      'etime' => '0',
      'euser' => '',
    ),
  ),
  'i' => 
  array (
    'inadm' => 
    array (
      'kid' => 'inadm',
      'pid' => '0',
      'title' => '管理部',
      'deep' => '1',
      'frame' => '0',
      'char' => 'G',
      'cfgs' => '',
    ),
    'intech' => 
    array (
      'kid' => 'intech',
      'pid' => '0',
      'title' => '技术部',
      'deep' => '1',
      'frame' => '0',
      'char' => 'J',
      'cfgs' => '',
    ),
    'incai' => 
    array (
      'kid' => 'incai',
      'pid' => '0',
      'title' => '财务部',
      'deep' => '1',
      'frame' => '0',
      'char' => 'C',
      'cfgs' => '',
    ),
    'inbus' => 
    array (
      'kid' => 'inbus',
      'pid' => '0',
      'title' => '业务部',
      'deep' => '1',
      'frame' => '0',
      'char' => 'Y',
      'cfgs' => '',
    ),
    'inpro' => 
    array (
      'kid' => 'inpro',
      'pid' => '0',
      'title' => '生产部',
      'deep' => '1',
      'frame' => '0',
      'char' => 'S',
      'cfgs' => '',
    ),
    'inren' => 
    array (
      'kid' => 'inren',
      'pid' => '0',
      'title' => '人力部',
      'deep' => '1',
      'frame' => '0',
      'char' => 'R',
      'cfgs' => '',
    ),
  ),
);
?>