<?php
$_natcn = array (
  'kid' => 'natcn',
  'pid' => 'types',
  'title' => '民族',
  'enable' => '1',
  'etab' => '1',
  'deep' => '1',
  'cfgs' => 'exdoc=1',
  'f' => 
  array (
    'renkou' => 
    array (
      'kid' => 'renkou',
      'model' => 'natcn',
      'title' => '人口',
      'top' => '120',
      'enable' => '1',
      'etab' => '0',
      'type' => 'input',
      'dbtype' => 'int',
      'dblen' => '12',
      'dbdef' => '',
      'vreg' => 'nul:n+d',
      'vtip' => '数字,单位(万)',
      'vmax' => '12',
      'fmsize' => '',
      'fmline' => '1',
      'fmtitle' => '0',
      'fmextra' => '',
      'fmexstr' => '',
      'cfgs' => '',
      'note' => '',
      'aip' => '',
      'atime' => '0',
      'auser' => '',
      'eip' => '',
      'etime' => '0',
      'euser' => '',
    ),
    'detail' => 
    array (
      'kid' => 'detail',
      'model' => 'natcn',
      'title' => '简介',
      'top' => '888',
      'enable' => '1',
      'etab' => '0',
      'type' => 'text',
      'dbtype' => 'text',
      'dblen' => '0',
      'dbdef' => '',
      'vreg' => 'nul:str:0-255',
      'vtip' => '',
      'vmax' => '255',
      'fmsize' => '360x6',
      'fmline' => '1',
      'fmtitle' => '0',
      'fmextra' => '',
      'fmexstr' => '',
      'cfgs' => '',
      'note' => '',
      'aip' => '',
      'atime' => '0',
      'auser' => '',
      'eip' => '',
      'etime' => '0',
      'euser' => '',
    ),
  ),
  'i' => 
  array (
    'han' => 
    array (
      'kid' => 'han',
      'pid' => '0',
      'title' => '汉族',
      'deep' => '1',
      'frame' => '0',
      'char' => 'H',
      'cfgs' => '',
    ),
    'zhuang' => 
    array (
      'kid' => 'zhuang',
      'pid' => '0',
      'title' => '壮族',
      'deep' => '1',
      'frame' => '0',
      'char' => 'Z',
      'cfgs' => '',
    ),
    'man' => 
    array (
      'kid' => 'man',
      'pid' => '0',
      'title' => '满族',
      'deep' => '1',
      'frame' => '0',
      'char' => 'M',
      'cfgs' => '',
    ),
    'hui' => 
    array (
      'kid' => 'hui',
      'pid' => '0',
      'title' => '回族',
      'deep' => '1',
      'frame' => '0',
      'char' => 'H',
      'cfgs' => '',
    ),
    'miao' => 
    array (
      'kid' => 'miao',
      'pid' => '0',
      'title' => '苗族',
      'deep' => '1',
      'frame' => '0',
      'char' => 'M',
      'cfgs' => '',
    ),
    'wei' => 
    array (
      'kid' => 'wei',
      'pid' => '0',
      'title' => '维吾尔族',
      'deep' => '1',
      'frame' => '0',
      'char' => 'W',
      'cfgs' => '',
    ),
    'tuj' => 
    array (
      'kid' => 'tuj',
      'pid' => '0',
      'title' => '土家族',
      'deep' => '1',
      'frame' => '0',
      'char' => 'T',
      'cfgs' => '',
    ),
    'yizu' => 
    array (
      'kid' => 'yizu',
      'pid' => '0',
      'title' => '彝族',
      'deep' => '1',
      'frame' => '0',
      'char' => 'Y',
      'cfgs' => '',
    ),
    'meng' => 
    array (
      'kid' => 'meng',
      'pid' => '0',
      'title' => '蒙古族',
      'deep' => '1',
      'frame' => '0',
      'char' => 'M',
      'cfgs' => '',
    ),
    'zang' => 
    array (
      'kid' => 'zang',
      'pid' => '0',
      'title' => '藏族',
      'deep' => '1',
      'frame' => '0',
      'char' => 'C',
      'cfgs' => '',
    ),
    'buyi' => 
    array (
      'kid' => 'buyi',
      'pid' => '0',
      'title' => '布依族',
      'deep' => '1',
      'frame' => '0',
      'char' => 'B',
      'cfgs' => '',
    ),
    'yao' => 
    array (
      'kid' => 'yao',
      'pid' => '0',
      'title' => '瑶族',
      'deep' => '1',
      'frame' => '0',
      'char' => 'Y',
      'cfgs' => '',
    ),
    'chao' => 
    array (
      'kid' => 'chao',
      'pid' => '0',
      'title' => '朝鲜族',
      'deep' => '1',
      'frame' => '0',
      'char' => 'C',
      'cfgs' => '',
    ),
    'bai' => 
    array (
      'kid' => 'bai',
      'pid' => '0',
      'title' => '白族',
      'deep' => '1',
      'frame' => '0',
      'char' => 'B',
      'cfgs' => '',
    ),
    'hali' => 
    array (
      'kid' => 'hali',
      'pid' => '0',
      'title' => '哈尼族',
      'deep' => '1',
      'frame' => '0',
      'char' => 'H',
      'cfgs' => '',
    ),
    'hsk' => 
    array (
      'kid' => 'hsk',
      'pid' => '0',
      'title' => '哈萨克族',
      'deep' => '1',
      'frame' => '0',
      'char' => 'H',
      'cfgs' => '',
    ),
    'dai' => 
    array (
      'kid' => 'dai',
      'pid' => '0',
      'title' => '傣族',
      'deep' => '1',
      'frame' => '0',
      'char' => 'D',
      'cfgs' => '',
    ),
    'dong' => 
    array (
      'kid' => 'dong',
      'pid' => '0',
      'title' => '东乡族',
      'deep' => '1',
      'frame' => '0',
      'char' => 'D',
      'cfgs' => '',
    ),
    'she' => 
    array (
      'kid' => 'she',
      'pid' => '0',
      'title' => '畲族',
      'deep' => '1',
      'frame' => '0',
      'char' => 'S',
      'cfgs' => '',
    ),
    'lisu' => 
    array (
      'kid' => 'lisu',
      'pid' => '0',
      'title' => '傈僳族',
      'deep' => '1',
      'frame' => '0',
      'char' => 'L',
      'cfgs' => '',
    ),
    'gelao' => 
    array (
      'kid' => 'gelao',
      'pid' => '0',
      'title' => '仡佬族',
      'deep' => '1',
      'frame' => '0',
      'char' => 'Y',
      'cfgs' => '',
    ),
    'lagu' => 
    array (
      'kid' => 'lagu',
      'pid' => '0',
      'title' => '拉祜族',
      'deep' => '1',
      'frame' => '0',
      'char' => 'L',
      'cfgs' => '',
    ),
    'tong' => 
    array (
      'kid' => 'tong',
      'pid' => '0',
      'title' => '侗族',
      'deep' => '1',
      'frame' => '0',
      'char' => 'D',
      'cfgs' => '',
    ),
    'tuzu' => 
    array (
      'kid' => 'tuzu',
      'pid' => '0',
      'title' => '土族',
      'deep' => '1',
      'frame' => '0',
      'char' => 'T',
      'cfgs' => '',
    ),
    'lizu' => 
    array (
      'kid' => 'lizu',
      'pid' => '0',
      'title' => '黎族',
      'deep' => '1',
      'frame' => '0',
      'char' => 'L',
      'cfgs' => '',
    ),
    'jing' => 
    array (
      'kid' => 'jing',
      'pid' => '0',
      'title' => '京族',
      'deep' => '1',
      'frame' => '0',
      'char' => 'J',
      'cfgs' => '',
    ),
    'gao' => 
    array (
      'kid' => 'gao',
      'pid' => '0',
      'title' => '高山族',
      'deep' => '1',
      'frame' => '0',
      'char' => 'G',
      'cfgs' => '',
    ),
    'shui' => 
    array (
      'kid' => 'shui',
      'pid' => '0',
      'title' => '水族',
      'deep' => '1',
      'frame' => '0',
      'char' => 'S',
      'cfgs' => '',
    ),
    'wazu' => 
    array (
      'kid' => 'wazu',
      'pid' => '0',
      'title' => '佤族',
      'deep' => '1',
      'frame' => '0',
      'char' => 'W',
      'cfgs' => '',
    ),
    'nazu' => 
    array (
      'kid' => 'nazu',
      'pid' => '0',
      'title' => '纳西族',
      'deep' => '1',
      'frame' => '0',
      'char' => 'N',
      'cfgs' => '',
    ),
    'qiang' => 
    array (
      'kid' => 'qiang',
      'pid' => '0',
      'title' => '羌族',
      'deep' => '1',
      'frame' => '0',
      'char' => 'Q',
      'cfgs' => '',
    ),
    'melao' => 
    array (
      'kid' => 'melao',
      'pid' => '0',
      'title' => '仫佬族',
      'deep' => '1',
      'frame' => '0',
      'char' => 'M',
      'cfgs' => '',
    ),
    'xibo' => 
    array (
      'kid' => 'xibo',
      'pid' => '0',
      'title' => '锡伯族',
      'deep' => '1',
      'frame' => '0',
      'char' => 'X',
      'cfgs' => '',
    ),
    'kerkz' => 
    array (
      'kid' => 'kerkz',
      'pid' => '0',
      'title' => '柯尔克孜族',
      'deep' => '1',
      'frame' => '0',
      'char' => 'K',
      'cfgs' => '',
    ),
    'dagan' => 
    array (
      'kid' => 'dagan',
      'pid' => '0',
      'title' => '达斡尔族',
      'deep' => '1',
      'frame' => '0',
      'char' => 'D',
      'cfgs' => '',
    ),
    'jpo' => 
    array (
      'kid' => 'jpo',
      'pid' => '0',
      'title' => '景颇族',
      'deep' => '1',
      'frame' => '0',
      'char' => 'J',
      'cfgs' => '',
    ),
    'mao' => 
    array (
      'kid' => 'mao',
      'pid' => '0',
      'title' => '毛南族',
      'deep' => '1',
      'frame' => '0',
      'char' => 'M',
      'cfgs' => '',
    ),
    'sala' => 
    array (
      'kid' => 'sala',
      'pid' => '0',
      'title' => '撒拉族',
      'deep' => '1',
      'frame' => '0',
      'char' => 'S',
      'cfgs' => '',
    ),
    'bul' => 
    array (
      'kid' => 'bul',
      'pid' => '0',
      'title' => '布朗族',
      'deep' => '1',
      'frame' => '0',
      'char' => 'B',
      'cfgs' => '',
    ),
    'djk' => 
    array (
      'kid' => 'djk',
      'pid' => '0',
      'title' => '塔吉克族',
      'deep' => '1',
      'frame' => '0',
      'char' => 'T',
      'cfgs' => '',
    ),
    'ach' => 
    array (
      'kid' => 'ach',
      'pid' => '0',
      'title' => '阿昌族',
      'deep' => '1',
      'frame' => '0',
      'char' => 'A',
      'cfgs' => '',
    ),
    'pumi' => 
    array (
      'kid' => 'pumi',
      'pid' => '0',
      'title' => '普米族',
      'deep' => '1',
      'frame' => '0',
      'char' => 'P',
      'cfgs' => '',
    ),
    'ewen' => 
    array (
      'kid' => 'ewen',
      'pid' => '0',
      'title' => '鄂温克族',
      'deep' => '1',
      'frame' => '0',
      'char' => 'E',
      'cfgs' => '',
    ),
    'nuzu' => 
    array (
      'kid' => 'nuzu',
      'pid' => '0',
      'title' => '怒族',
      'deep' => '1',
      'frame' => '0',
      'char' => 'N',
      'cfgs' => '',
    ),
    'jinuo' => 
    array (
      'kid' => 'jinuo',
      'pid' => '0',
      'title' => '基诺族',
      'deep' => '1',
      'frame' => '0',
      'char' => 'J',
      'cfgs' => '',
    ),
    'deang' => 
    array (
      'kid' => 'deang',
      'pid' => '0',
      'title' => '德昂族',
      'deep' => '1',
      'frame' => '0',
      'char' => 'D',
      'cfgs' => '',
    ),
    'baoa' => 
    array (
      'kid' => 'baoa',
      'pid' => '0',
      'title' => '保安族',
      'deep' => '1',
      'frame' => '0',
      'char' => 'B',
      'cfgs' => '',
    ),
    'els' => 
    array (
      'kid' => 'els',
      'pid' => '0',
      'title' => '俄罗斯族',
      'deep' => '1',
      'frame' => '0',
      'char' => 'E',
      'cfgs' => '',
    ),
    'yugu' => 
    array (
      'kid' => 'yugu',
      'pid' => '0',
      'title' => '裕固族',
      'deep' => '1',
      'frame' => '0',
      'char' => 'Y',
      'cfgs' => '',
    ),
    'wzbk' => 
    array (
      'kid' => 'wzbk',
      'pid' => '0',
      'title' => '乌兹别克族',
      'deep' => '1',
      'frame' => '0',
      'char' => 'W',
      'cfgs' => '',
    ),
    'mba' => 
    array (
      'kid' => 'mba',
      'pid' => '0',
      'title' => '门巴族',
      'deep' => '1',
      'frame' => '0',
      'char' => 'M',
      'cfgs' => '',
    ),
    'elc' => 
    array (
      'kid' => 'elc',
      'pid' => '0',
      'title' => '鄂伦春族',
      'deep' => '1',
      'frame' => '0',
      'char' => 'E',
      'cfgs' => '',
    ),
    'dul' => 
    array (
      'kid' => 'dul',
      'pid' => '0',
      'title' => '独龙族',
      'deep' => '1',
      'frame' => '0',
      'char' => 'D',
      'cfgs' => '',
    ),
    'tter' => 
    array (
      'kid' => 'tter',
      'pid' => '0',
      'title' => '塔塔尔族',
      'deep' => '1',
      'frame' => '0',
      'char' => 'T',
      'cfgs' => '',
    ),
    'hez' => 
    array (
      'kid' => 'hez',
      'pid' => '0',
      'title' => '赫哲族',
      'deep' => '1',
      'frame' => '0',
      'char' => 'H',
      'cfgs' => '',
    ),
    'geba' => 
    array (
      'kid' => 'geba',
      'pid' => '0',
      'title' => '珞巴族',
      'deep' => '1',
      'frame' => '0',
      'char' => 'L',
      'cfgs' => '',
    ),
    'qita' => 
    array (
      'kid' => 'qita',
      'pid' => '0',
      'title' => '其它',
      'deep' => '1',
      'frame' => '0',
      'char' => 'Q',
      'cfgs' => '',
    ),
  ),
);
?>