<?php
$_prcore = array (
  'kid' => 'prcore',
  'pid' => 'score',
  'title' => '核心设置',
  'enable' => '1',
  'etab' => '0',
  'deep' => '1',
  'f' => 
  array (
    'sys_editor' => 
    array (
      'kid' => 'sys_editor',
      'title' => '系统编辑器',
      'etab' => '0',
      'type' => 'select',
      'dbtype' => 'varchar',
      'dblen' => '12',
      'dbdef' => 'kind',
      'vreg' => 'str:2-12',
      'vtip' => '',
      'vmax' => '12',
      'fmsize' => '',
      'fmline' => '1',
      'fmtitle' => '0',
      'fmextra' => '',
      'fmexstr' => '',
      'cfgs' => 'kind=KindEditor
sn=Summernote
ue=UEditor
um=UEMini
ck=CKEditor
xh=xhEditor',
      'key' => 'sys_editor',
      'val' => 'summernote',
    ),
    'sys_open' => 
    array (
      'kid' => 'sys_open',
      'title' => 'open开窗方式',
      'etab' => '0',
      'type' => 'select',
      'dbtype' => 'varchar',
      'dblen' => '12',
      'dbdef' => '4',
      'vreg' => 'n+i',
      'vtip' => '',
      'vmax' => '12',
      'fmsize' => '',
      'fmline' => '1',
      'fmtitle' => '0',
      'fmextra' => '',
      'fmexstr' => '',
      'cfgs' => '4=4)layer@sentsin.com(推荐)
1=1)Js/window.open',
      'key' => 'sys_open',
      'val' => '4',
    ),
    'sys_pop' => 
    array (
      'kid' => 'sys_pop',
      'title' => 'pop开窗方式',
      'etab' => '0',
      'type' => 'select',
      'dbtype' => 'varchar',
      'dblen' => '12',
      'dbdef' => '3',
      'vreg' => 'n+i',
      'vtip' => '',
      'vmax' => '12',
      'fmsize' => '',
      'fmline' => '1',
      'fmtitle' => '0',
      'fmextra' => '',
      'fmexstr' => '',
      'cfgs' => '4=4)layer@sentsin.com
3=3)JQ/tipsWindown(推荐)',
      'key' => 'sys_pop',
      'val' => '3',
    ),
    'msg_timea' => 
    array (
      'kid' => 'msg_timea',
      'title' => '提示停留时间',
      'etab' => '0',
      'type' => 'input',
      'dbtype' => 'int',
      'dblen' => '255',
      'dbdef' => '1500',
      'vreg' => 'n+i',
      'vtip' => '毫秒',
      'vmax' => '12',
      'fmsize' => '',
      'fmline' => '1',
      'fmtitle' => '0',
      'fmextra' => '',
      'fmexstr' => '',
      'cfgs' => '',
      'key' => 'msg_timea',
      'val' => '1500',
    ),
    'sys_map' => 
    array (
      'kid' => 'sys_map',
      'title' => '地图API',
      'etab' => '0',
      'type' => 'select',
      'dbtype' => 'varchar',
      'dblen' => '12',
      'dbdef' => 'baidu',
      'vreg' => 'str:2-12',
      'vtip' => '',
      'vmax' => '12',
      'fmsize' => '',
      'fmline' => '1',
      'fmtitle' => '0',
      'fmextra' => '',
      'fmexstr' => '',
      'cfgs' => 'baidu=百度
google=Google',
      'key' => 'sys_map',
      'val' => 'baidu',
    ),
    'sys_name' => 
    array (
      'kid' => 'sys_name',
      'title' => '站点名称',
      'etab' => '0',
      'type' => 'input',
      'dbtype' => 'varchar',
      'dblen' => '24',
      'dbdef' => '',
      'vreg' => 'str:2-255',
      'vtip' => '',
      'vmax' => '255',
      'fmsize' => '',
      'fmline' => '1',
      'fmtitle' => '0',
      'fmextra' => '',
      'fmexstr' => '',
      'cfgs' => '',
      'key' => 'sys_name',
      'val' => '贴心猫(IntimateCat)',
    ),
  ),
);
?>