<?php
$_prbase = array (
  'kid' => 'prbase',
  'pid' => 'score',
  'title' => '基本开关',
  'enable' => '1',
  'etab' => '0',
  'deep' => '1',
  'f' => 
  array (
    'adm_mode' => 
    array (
      'title' => '系统管理模式',
      'enable' => '1',
      'etab' => '0',
      'type' => 'input',
      'dbtype' => 'varchar',
      'dblen' => '12',
      'dbdef' => '',
      'vreg' => 'str:2-255',
      'vtip' => '',
      'vmax' => '24',
      'fmsize' => '',
      'fmline' => '1',
      'fmtitle' => '0',
      'key' => 'adm_mode',
    ),
    'debug_mode' => 
    array (
      'title' => '调试模式',
      'enable' => '1',
      'etab' => '0',
      'type' => 'radio',
      'dbtype' => 'varchar',
      'dblen' => '12',
      'dbdef' => '',
      'vreg' => 'str:2-12',
      'vtip' => '',
      'vmax' => '12',
      'fmsize' => '',
      'fmline' => '1',
      'fmtitle' => '0',
      'key' => '[debug][err_mode]',
      'cfgs' => '0=关闭
1=调试',
    ),
    'close_chn' => 
    array (
      'title' => '关闭chn显示模板',
      'enable' => '1',
      'etab' => '0',
      'type' => 'radio',
      'dbtype' => 'varchar',
      'dblen' => '12',
      'dbdef' => '',
      'vreg' => 'str:2-12',
      'vtip' => '',
      'vmax' => '12',
      'fmsize' => '500x6',
      'fmline' => '1',
      'fmtitle' => '0',
      'key' => 'close_chn',
      'cfgs' => '0=开启
1=关闭',
    ),
    'close_mob' => 
    array (
      'title' => '关闭mob显示模板',
      'enable' => '1',
      'etab' => '0',
      'type' => 'radio',
      'dbtype' => 'varchar',
      'dblen' => '12',
      'dbdef' => '',
      'vreg' => 'str:2-12',
      'vtip' => '',
      'vmax' => '12',
      'fmsize' => '500x6',
      'fmline' => '1',
      'fmtitle' => '0',
      'key' => 'close_mob',
      'cfgs' => '0=开启
1=关闭',
    ),
    'close_dev' => 
    array (
      'title' => '关闭dev显示模板',
      'enable' => '1',
      'etab' => '0',
      'type' => 'radio',
      'dbtype' => 'varchar',
      'dblen' => '12',
      'dbdef' => '',
      'vreg' => 'str:2-12',
      'vtip' => '',
      'vmax' => '12',
      'fmsize' => '500x6',
      'fmline' => '1',
      'fmtitle' => '0',
      'key' => 'close_dev',
      'cfgs' => '0=开启
1=关闭',
    ),
    'login_dev' => 
    array (
      'title' => '显示dev需登录',
      'enable' => '1',
      'etab' => '0',
      'type' => 'radio',
      'dbtype' => 'varchar',
      'dblen' => '12',
      'dbdef' => '',
      'vreg' => 'str:2-12',
      'vtip' => '',
      'vmax' => '12',
      'fmsize' => '500x6',
      'fmline' => '1',
      'fmtitle' => '0',
      'key' => 'login_dev',
      'cfgs' => 'adminer=仅管理员
member=会员登录
0=不需登录',
    ),
  ),
);
?>