<?php
$_grade = array (
  'supper' => 
  array (
    'kid' => 'supper',
    'model' => 'adminer',
    'title' => '超级管理员',
    'pmadm' => '',
    'pmusr' => 'm1base,m2uedit,m2upass,m2uinfo,m2utips,m1order,m2order,m2oitem,m2oquiry,m1docs,m2idview,m2idpub',
    'pfile' => '',
    'pmod' => '',
    'padd' => '',
    'pdel' => '',
    'pcheck' => '',
    'pextra' => '',
    'cfgs' => '',
    'grade' => 'supper',
  ),
  'ainfo' => 
  array (
    'kid' => 'ainfo',
    'model' => 'adminer',
    'title' => '信息管理员',
    'pmadm' => 'm1inf,m1app,m1adm,m2fav,m2adm,m3012,m2016,m2020',
    'pmusr' => 'order-isdone,indoc-get,indoc-d,indoc-adm',
    'pfile' => 'admin/paras.php,admin/api400.php',
    'pmod' => 'person,lnkpic,apisms,apipay,apimail,apijihua',
    'padd' => 'about,gbook',
    'pdel' => 'news,snote',
    'pcheck' => 'about,snote',
    'pextra' => 'pstools,psdev',
    'cfgs' => 'upsize1=200
upsizes=960000',
    'grade' => 'ainfo',
  ),
  'auser' => 
  array (
    'kid' => 'auser',
    'model' => 'adminer',
    'title' => '会员管理员',
    'pmadm' => '',
    'pmusr' => 'm1base,m2uedit,m2upass,m2uinfo,m2utips,m1order,m2order,m2oitem,m2oquiry,m1docs,m2idview,m2idpub',
    'pfile' => '',
    'pmod' => '',
    'padd' => '',
    'pdel' => '',
    'pcheck' => '',
    'pextra' => '',
    'cfgs' => '',
    'grade' => 'auser',
  ),
  'advers' => 
  array (
    'kid' => 'advers',
    'model' => 'adminer',
    'title' => '广告管理员',
    'pmadm' => '',
    'pmusr' => 'm1base,m2uedit,m2upass,m2uinfo,m2utips,m1order,m2order,m2oitem,m2oquiry,m1docs,m2idview,m2idpub',
    'pfile' => '',
    'pmod' => '',
    'padd' => '',
    'pdel' => '',
    'pcheck' => '',
    'pextra' => '',
    'cfgs' => '',
    'grade' => 'advers',
  ),
  'aframe' => 
  array (
    'kid' => 'aframe',
    'model' => 'adminer',
    'title' => '系统架构员',
    'pmadm' => '',
    'pmusr' => 'm1base,m2uedit,m2upass,m2uinfo,m2utips,m1order,m2order,m2oitem,m2oquiry,m1docs,m2idview,m2idpub',
    'pfile' => '',
    'pmod' => '',
    'padd' => '',
    'pdel' => '',
    'pcheck' => '',
    'pextra' => '',
    'cfgs' => '',
    'grade' => 'aframe',
  ),
  'aperm' => 
  array (
    'kid' => 'aperm',
    'model' => 'adminer',
    'title' => '权限测试员',
    'pmadm' => 'm1edu,m1inf',
    'pmusr' => 'm1base,m2uedit,m2upass,m2uinfo,m2utips,m1order,m2order,m2oitem,m2oquiry,m1docs,m2idview,m2idpub',
    'pfile' => 'admin/menus.php,admin/apisms.php',
    'pmod' => 'demo,nrem',
    'padd' => 'about,gbook',
    'pdel' => 'news,snote',
    'pcheck' => 'pro',
    'pextra' => 'edtlist,edtup,edtadm',
    'cfgs' => '',
    'grade' => 'aperm',
  ),
  'astop' => 
  array (
    'kid' => 'astop',
    'model' => 'adminer',
    'title' => '过期管理员',
    'pmadm' => '',
    'pmusr' => 'm1base,m2uedit,m2upass,m2uinfo,m2utips,m1order,m2order,m2oitem,m2oquiry,m1docs,m2idview,m2idpub',
    'pfile' => '',
    'pmod' => '',
    'padd' => '',
    'pdel' => '',
    'pcheck' => '',
    'pextra' => '',
    'cfgs' => '',
    'grade' => 'astop',
  ),
  'ccom' => 
  array (
    'kid' => 'ccom',
    'model' => 'company',
    'title' => '普通企业',
    'pmadm' => '',
    'pmusr' => 'm1base,m2uedit,m2upass,m2uinfo,m2utips,m1order,m2order,m2oitem,m2oquiry,m1docs,m2idview,m2idpub',
    'pfile' => '',
    'pmod' => 'demo,about',
    'padd' => '',
    'pdel' => '',
    'pcheck' => '',
    'pextra' => 'edtlist,edtup,edtadm,pstools,psdev,image,flash,media,docus',
    'cfgs' => 'upsize1=200
upsizes=960000',
    'grade' => 'ccom',
  ),
  'cvip' => 
  array (
    'kid' => 'cvip',
    'model' => 'company',
    'title' => 'VIP企业',
    'pmadm' => '',
    'pmusr' => 'm1base,m2uedit,m2upass,m2uinfo,m2utips,m1order,m2order,m2oitem,m2oquiry,m1docs,m2idview,m2idpub',
    'pfile' => '',
    'pmod' => '',
    'padd' => '',
    'pdel' => '',
    'pcheck' => '',
    'pextra' => 'edtlist,edtup,edtadm',
    'cfgs' => 'tplname=c_mod/mem_detailvip
tplnamenews=c_mod/mem_ulstvip',
    'grade' => 'cvip',
  ),
  'cstop' => 
  array (
    'kid' => 'cstop',
    'model' => 'company',
    'title' => '过期企业',
    'pmadm' => '',
    'pmusr' => 'm1base,m2uedit,m2upass,m2uinfo,m2utips,m1order,m2order,m2oitem,m2oquiry,m1docs,m2idview,m2idpub',
    'pfile' => '',
    'pmod' => '',
    'padd' => '',
    'pdel' => '',
    'pcheck' => '',
    'pextra' => '',
    'cfgs' => '',
    'grade' => 'cstop',
  ),
  'gcom' => 
  array (
    'kid' => 'gcom',
    'model' => 'govern',
    'title' => '一般机构',
    'pmadm' => '',
    'pmusr' => 'm1base,m2uedit,m2upass,m2uinfo,m2utips,m1order,m2order,m2oitem,m2oquiry,m1docs,m2idview,m2idpub',
    'pfile' => '',
    'pmod' => '',
    'padd' => '',
    'pdel' => '',
    'pcheck' => '',
    'pextra' => '',
    'cfgs' => '',
    'grade' => 'gcom',
  ),
  'gvip' => 
  array (
    'kid' => 'gvip',
    'model' => 'govern',
    'title' => 'VIP机构',
    'pmadm' => '',
    'pmusr' => 'm1base,m2uedit,m2upass,m2uinfo,m2utips,m1order,m2order,m2oitem,m2oquiry,m1docs,m2idview,m2idpub',
    'pfile' => '',
    'pmod' => '',
    'padd' => '',
    'pdel' => '',
    'pcheck' => '',
    'pextra' => '',
    'cfgs' => '',
    'grade' => 'gvip',
  ),
  'gstop' => 
  array (
    'kid' => 'gstop',
    'model' => 'govern',
    'title' => '禁用机构',
    'pmadm' => '',
    'pmusr' => 'm1base,m2uedit,m2upass,m2uinfo,m2utips,m1order,m2order,m2oitem,m2oquiry,m1docs,m2idview,m2idpub',
    'pfile' => '',
    'pmod' => '',
    'padd' => '',
    'pdel' => '',
    'pcheck' => '',
    'pextra' => '',
    'cfgs' => '',
    'grade' => 'gstop',
  ),
  'inadm' => 
  array (
    'kid' => 'inadm',
    'model' => 'inmem',
    'title' => '超级会员',
    'pmadm' => '',
    'pmusr' => 'm1base,m2uedit,m2upass,m2uinfo,m2utips,m1order,m2order,m2oitem,m2oquiry,m1docs,m2idview,m2idpub',
    'pfile' => '',
    'pmod' => '',
    'padd' => '',
    'pdel' => '',
    'pcheck' => '',
    'pextra' => '',
    'cfgs' => '',
    'grade' => 'inadm',
  ),
  'incom' => 
  array (
    'kid' => 'incom',
    'model' => 'inmem',
    'title' => '普通会员',
    'pmadm' => '',
    'pmusr' => 'm1base,m2uedit,m2upass,m2uinfo,m2utips,m1order,m2order,m2oitem,m2oquiry,m1docs,m2idview,m2idpub',
    'pfile' => '',
    'pmod' => '',
    'padd' => '',
    'pdel' => '',
    'pcheck' => '',
    'pextra' => '',
    'cfgs' => '',
    'grade' => 'incom',
  ),
  'instop' => 
  array (
    'kid' => 'instop',
    'model' => 'inmem',
    'title' => '过期会员',
    'pmadm' => '',
    'pmusr' => 'm1base,m2uedit,m2upass,m2uinfo,m2utips,m1order,m2order,m2oitem,m2oquiry,m1docs,m2idview,m2idpub',
    'pfile' => '',
    'pmod' => '',
    'padd' => '',
    'pdel' => '',
    'pcheck' => '',
    'pextra' => '',
    'cfgs' => '',
    'grade' => 'instop',
  ),
  'zcom' => 
  array (
    'kid' => 'zcom',
    'model' => 'organize',
    'title' => '一般组织',
    'pmadm' => '',
    'pmusr' => 'm1base,m2uedit,m2upass,m2uinfo,m2utips,m1order,m2order,m2oitem,m2oquiry,m1docs,m2idview,m2idpub',
    'pfile' => '',
    'pmod' => '',
    'padd' => '',
    'pdel' => '',
    'pcheck' => '',
    'pextra' => '',
    'cfgs' => 'upsize1=200
upsizes=960000',
    'grade' => 'zcom',
  ),
  'zvip' => 
  array (
    'kid' => 'zvip',
    'model' => 'organize',
    'title' => 'VIP组织',
    'pmadm' => '',
    'pmusr' => 'm1base,m2uedit,m2upass,m2uinfo,m2utips,m1order,m2order,m2oitem,m2oquiry,m1docs,m2idview,m2idpub',
    'pfile' => '',
    'pmod' => '',
    'padd' => '',
    'pdel' => '',
    'pcheck' => '',
    'pextra' => '',
    'cfgs' => '',
    'grade' => 'zvip',
  ),
  'zstop' => 
  array (
    'kid' => 'zstop',
    'model' => 'organize',
    'title' => '过期组织',
    'pmadm' => '',
    'pmusr' => 'm1base,m2uedit,m2upass,m2uinfo,m2utips,m1order,m2order,m2oitem,m2oquiry,m1docs,m2idview,m2idpub',
    'pfile' => '',
    'pmod' => '',
    'padd' => '',
    'pdel' => '',
    'pcheck' => '',
    'pextra' => '',
    'cfgs' => '',
    'grade' => 'zstop',
  ),
  'pcom' => 
  array (
    'kid' => 'pcom',
    'model' => 'person',
    'title' => '普通个人',
    'pmadm' => '',
    'pmusr' => 'm1base,m2uedit,m2upass,m2uinfo,m2utips,m1order,m2order,m2oitem,m2oquiry,m1docs,m2idview,m2idpub',
    'pfile' => '',
    'pmod' => '',
    'padd' => '',
    'pdel' => '',
    'pcheck' => '',
    'pextra' => '',
    'cfgs' => '',
    'grade' => 'pcom',
  ),
  'pvip' => 
  array (
    'kid' => 'pvip',
    'model' => 'person',
    'title' => 'VIP个人',
    'pmadm' => '',
    'pmusr' => 'm1base,m2uedit,m2upass,m2uinfo,m2utips,m1order,m2order,m2oitem,m2oquiry,m1docs,m2idview,m2idpub',
    'pfile' => '',
    'pmod' => '',
    'padd' => '',
    'pdel' => '',
    'pcheck' => '',
    'pextra' => '',
    'cfgs' => '',
    'grade' => 'pvip',
  ),
  'pstop' => 
  array (
    'kid' => 'pstop',
    'model' => 'person',
    'title' => '过期个人',
    'pmadm' => '',
    'pmusr' => 'm1base,m2uedit,m2upass,m2uinfo,m2utips,m1order,m2order,m2oitem,m2oquiry,m1docs,m2idview,m2idpub',
    'pfile' => '',
    'pmod' => '',
    'padd' => '',
    'pdel' => '',
    'pcheck' => '',
    'pextra' => '',
    'cfgs' => '',
    'grade' => 'pstop',
  ),
);
?>