<?php
$_c_about = array (
  'alink' => 
  array (
    'exp_i01' => 
    array (
      'kid' => 'exp_i01',
      'model' => 'about',
      'catid' => 'alink',
      'title' => '地图',
      'top' => '888',
      'enable' => '1',
      'etab' => '0',
      'type' => 'input',
      'dbtype' => 'varchar',
      'dblen' => '48',
      'dbdef' => '',
      'vreg' => 'nul:',
      'vtip' => '',
      'vmax' => '48',
      'fmsize' => '240',
      'fmline' => '1',
      'fmtitle' => '0',
      'fmextra' => 'map',
      'fmexstr' => '',
      'cfgs' => '',
      'note' => '',
      'aip' => '',
      'atime' => '0',
      'auser' => '',
      'eip' => '',
      'etime' => '0',
      'euser' => '',
    ),
  ),
  'apics' => 
  array (
    'exp_t01' => 
    array (
      'kid' => 'exp_t01',
      'model' => 'about',
      'catid' => 'apics',
      'title' => '图片集',
      'top' => '888',
      'enable' => '1',
      'etab' => '0',
      'type' => 'text',
      'dbtype' => 'text',
      'dblen' => '0',
      'dbdef' => '',
      'vreg' => 'nul:',
      'vtip' => '',
      'vmax' => '0',
      'fmsize' => '12',
      'fmline' => '1',
      'fmtitle' => '0',
      'fmextra' => 'pics',
      'fmexstr' => '',
      'cfgs' => '',
      'note' => '',
      'aip' => '',
      'atime' => '0',
      'auser' => '',
      'eip' => '',
      'etime' => '0',
      'euser' => '',
    ),
  ),
);
?>