<?php
$_c_cargo = array (
  'c2018' => 
  array (
    'exp_s01' => 
    array (
      'kid' => 'exp_s01',
      'model' => 'cargo',
      'catid' => 'c2018',
      'title' => '薄厚',
      'top' => '120',
      'enable' => '1',
      'etab' => '0',
      'type' => 'select',
      'dbtype' => 'varchar',
      'dblen' => '12',
      'dbdef' => '',
      'vreg' => '',
      'vtip' => '',
      'vmax' => '12',
      'fmsize' => '',
      'fmline' => '1',
      'fmtitle' => '0',
      'fmextra' => '',
      'fmexstr' => '',
      'cfgs' => 'chaobao=超薄杯
baobei=薄杯
zhonghe=中厚杯
hemo=厚模杯
jiahou=加厚杯
shuidai=水袋杯
shboxiahe=上薄下厚杯',
      'note' => '',
      'aip' => '',
      'atime' => '0',
      'auser' => '',
      'eip' => '',
      'etime' => '0',
      'euser' => '',
    ),
    'exp_s02' => 
    array (
      'kid' => 'exp_s02',
      'model' => 'cargo',
      'catid' => 'c2018',
      'title' => '材质',
      'top' => '140',
      'enable' => '1',
      'etab' => '0',
      'type' => 'select',
      'dbtype' => 'varchar',
      'dblen' => '12',
      'dbdef' => '',
      'vreg' => '',
      'vtip' => '',
      'vmax' => '12',
      'fmsize' => '',
      'fmline' => '0',
      'fmtitle' => '1',
      'fmextra' => '',
      'fmexstr' => '',
      'cfgs' => 'mobei=模杯
wufangbu=无纺布杯
shuidai=水袋杯 
leisi=蕾丝超薄杯',
      'note' => '',
      'aip' => '',
      'atime' => '0',
      'auser' => '',
      'eip' => '',
      'etime' => '0',
      'euser' => '',
    ),
    'exp_s03' => 
    array (
      'kid' => 'exp_s03',
      'model' => 'cargo',
      'catid' => 'c2018',
      'title' => '杯型',
      'top' => '160',
      'enable' => '1',
      'etab' => '0',
      'type' => 'select',
      'dbtype' => 'varchar',
      'dblen' => '12',
      'dbdef' => '',
      'vreg' => '',
      'vtip' => '',
      'vmax' => '12',
      'fmsize' => '',
      'fmline' => '1',
      'fmtitle' => '0',
      'fmextra' => '',
      'fmexstr' => '',
      'cfgs' => 'bei43=3/4杯
bei44=4/4杯
bei12=1/2杯
moxiong=抹胸
shenv=深V
sanjiao=三角杯',
      'note' => '',
      'aip' => '',
      'atime' => '0',
      'auser' => '',
      'eip' => '',
      'etime' => '0',
      'euser' => '',
    ),
    'exp_s04' => 
    array (
      'kid' => 'exp_s04',
      'model' => 'cargo',
      'catid' => 'c2018',
      'title' => '功能',
      'top' => '180',
      'enable' => '1',
      'etab' => '0',
      'type' => 'select',
      'dbtype' => 'varchar',
      'dblen' => '12',
      'dbdef' => '',
      'vreg' => '',
      'vtip' => '',
      'vmax' => '12',
      'fmsize' => '',
      'fmline' => '0',
      'fmtitle' => '1',
      'fmextra' => '',
      'fmexstr' => '',
      'cfgs' => 'julong=聚拢
wuheng=无痕
ceshou=侧收
dabei=大罩杯 
tuogao=托高
wugang=无钢托 
shushi=舒适 
meibei=美背 
qiankou=前系扣 
kezhaixie=可摘卸肩带',
      'note' => '',
      'aip' => '',
      'atime' => '0',
      'auser' => '',
      'eip' => '',
      'etime' => '0',
      'euser' => '',
    ),
  ),
  'c2020' => 
  array (
    'exp_s01' => 
    array (
      'kid' => 'exp_s01',
      'model' => 'cargo',
      'catid' => 'c2020',
      'title' => '款式',
      'top' => '120',
      'enable' => '1',
      'etab' => '0',
      'type' => 'select',
      'dbtype' => 'varchar',
      'dblen' => '12',
      'dbdef' => '',
      'vreg' => '',
      'vtip' => '',
      'vmax' => '12',
      'fmsize' => '',
      'fmline' => '1',
      'fmtitle' => '0',
      'fmextra' => '',
      'fmexstr' => '',
      'cfgs' => 'pingjiao=平角裤
sanjiao=三角裤
dingzi=丁字/T裤',
      'note' => '',
      'aip' => '',
      'atime' => '0',
      'auser' => '',
      'eip' => '',
      'etime' => '0',
      'euser' => '',
    ),
    'exp_s02' => 
    array (
      'kid' => 'exp_s02',
      'model' => 'cargo',
      'catid' => 'c2020',
      'title' => '尺码',
      'top' => '140',
      'enable' => '1',
      'etab' => '0',
      'type' => 'select',
      'dbtype' => 'varchar',
      'dblen' => '12',
      'dbdef' => '',
      'vreg' => '',
      'vtip' => '',
      'vmax' => '12',
      'fmsize' => '',
      'fmline' => '0',
      'fmtitle' => '1',
      'fmextra' => '',
      'fmexstr' => '',
      'cfgs' => 'sma=S码
mma=M码
lma=L码
xlma=XL码
xxlma=XXL码
xxxlma=XXXL码
dama=大码
chaodama=超大码
junma=均码',
      'note' => '',
      'aip' => '',
      'atime' => '0',
      'auser' => '',
      'eip' => '',
      'etime' => '0',
      'euser' => '',
    ),
  ),
  'p2012' => 
  array (
    'exp_s01' => 
    array (
      'kid' => 'exp_s01',
      'model' => 'cargo',
      'catid' => 'p2012',
      'title' => '手机类型',
      'top' => '120',
      'enable' => '1',
      'etab' => '0',
      'type' => 'select',
      'dbtype' => 'varchar',
      'dblen' => '12',
      'dbdef' => '',
      'vreg' => '',
      'vtip' => '',
      'vmax' => '12',
      'fmsize' => '120',
      'fmline' => '1',
      'fmtitle' => '0',
      'fmextra' => '',
      'fmexstr' => '',
      'cfgs' => 'zhineng=智能
net3g=3G
shangwu=商务
paizhao=拍照
laoren=老人',
      'note' => '',
      'aip' => '',
      'atime' => '0',
      'auser' => '',
      'eip' => '',
      'etime' => '0',
      'euser' => '',
    ),
    'exp_i01' => 
    array (
      'kid' => 'exp_i01',
      'model' => 'cargo',
      'catid' => 'p2012',
      'title' => '主屏尺寸',
      'top' => '140',
      'enable' => '1',
      'etab' => '0',
      'type' => 'input',
      'dbtype' => 'varchar',
      'dblen' => '24',
      'dbdef' => '',
      'vreg' => '',
      'vtip' => '',
      'vmax' => '24',
      'fmsize' => '180',
      'fmline' => '0',
      'fmtitle' => '1',
      'fmextra' => '',
      'fmexstr' => '',
      'cfgs' => '',
      'note' => '',
      'aip' => '',
      'atime' => '0',
      'auser' => '',
      'eip' => '',
      'etime' => '0',
      'euser' => '',
    ),
    'exp_s02' => 
    array (
      'kid' => 'exp_s02',
      'model' => 'cargo',
      'catid' => 'p2012',
      'title' => '核心数',
      'top' => '160',
      'enable' => '1',
      'etab' => '0',
      'type' => 'select',
      'dbtype' => 'varchar',
      'dblen' => '12',
      'dbdef' => '',
      'vreg' => '',
      'vtip' => '',
      'vmax' => '12',
      'fmsize' => '120',
      'fmline' => '1',
      'fmtitle' => '0',
      'fmextra' => '',
      'fmexstr' => '',
      'cfgs' => '1=单核
2=双核
4=四核
5=双四核
8=八核',
      'note' => '',
      'aip' => '',
      'atime' => '0',
      'auser' => '',
      'eip' => '',
      'etime' => '0',
      'euser' => '',
    ),
    'exp_i02' => 
    array (
      'kid' => 'exp_i02',
      'model' => 'cargo',
      'catid' => 'p2012',
      'title' => '操作系统',
      'top' => '180',
      'enable' => '1',
      'etab' => '0',
      'type' => 'input',
      'dbtype' => 'varchar',
      'dblen' => '24',
      'dbdef' => '',
      'vreg' => '',
      'vtip' => '',
      'vmax' => '24',
      'fmsize' => '180',
      'fmline' => '0',
      'fmtitle' => '1',
      'fmextra' => '',
      'fmexstr' => '',
      'cfgs' => '',
      'note' => '',
      'aip' => '',
      'atime' => '0',
      'auser' => '',
      'eip' => '',
      'etime' => '0',
      'euser' => '',
    ),
    'exp_m01' => 
    array (
      'kid' => 'exp_m01',
      'model' => 'cargo',
      'catid' => 'p2012',
      'title' => '外观颜色',
      'top' => '888',
      'enable' => '1',
      'etab' => '0',
      'type' => 'cbox',
      'dbtype' => 'varchar',
      'dblen' => '12',
      'dbdef' => '',
      'vreg' => 'nul:',
      'vtip' => '',
      'vmax' => '12',
      'fmsize' => '',
      'fmline' => '1',
      'fmtitle' => '0',
      'fmextra' => '',
      'fmexstr' => '',
      'cfgs' => 'bai=白色
hui=灰色
hei=黑色
lan=蓝色',
      'note' => '',
      'aip' => '',
      'atime' => '0',
      'auser' => '',
      'eip' => '',
      'etime' => '0',
      'euser' => '',
    ),
  ),
  'p2014' => 
  array (
    'exp_s01' => 
    array (
      'kid' => 'exp_s01',
      'model' => 'cargo',
      'catid' => 'p2014',
      'title' => '颜色',
      'top' => '120',
      'enable' => '1',
      'etab' => '0',
      'type' => 'select',
      'dbtype' => 'varchar',
      'dblen' => '12',
      'dbdef' => '',
      'vreg' => '',
      'vtip' => '',
      'vmax' => '12',
      'fmsize' => '120',
      'fmline' => '1',
      'fmtitle' => '0',
      'fmextra' => '',
      'fmexstr' => '',
      'cfgs' => 'bai=白色
hei=黑色
yin=银灰
kafei=咖啡
hong=红色
jing=金色
lan=蓝色',
      'note' => '',
      'aip' => '',
      'atime' => '0',
      'auser' => '',
      'eip' => '',
      'etime' => '0',
      'euser' => '',
    ),
    'exp_i01' => 
    array (
      'kid' => 'exp_i01',
      'model' => 'cargo',
      'catid' => 'p2014',
      'title' => '材质',
      'top' => '140',
      'enable' => '1',
      'etab' => '0',
      'type' => 'input',
      'dbtype' => 'varchar',
      'dblen' => '24',
      'dbdef' => '',
      'vreg' => '',
      'vtip' => '',
      'vmax' => '24',
      'fmsize' => '180',
      'fmline' => '0',
      'fmtitle' => '1',
      'fmextra' => '',
      'fmexstr' => '',
      'cfgs' => '',
      'note' => '',
      'aip' => '',
      'atime' => '0',
      'auser' => '',
      'eip' => '',
      'etime' => '0',
      'euser' => '',
    ),
    'exp_i02' => 
    array (
      'kid' => 'exp_i02',
      'model' => 'cargo',
      'catid' => 'p2014',
      'title' => '适用机型',
      'top' => '360',
      'enable' => '1',
      'etab' => '0',
      'type' => 'input',
      'dbtype' => 'varchar',
      'dblen' => '255',
      'dbdef' => '',
      'vreg' => '',
      'vtip' => '',
      'vmax' => '255',
      'fmsize' => '360',
      'fmline' => '1',
      'fmtitle' => '0',
      'fmextra' => '',
      'fmexstr' => '',
      'cfgs' => '',
      'note' => '',
      'aip' => '',
      'atime' => '0',
      'auser' => '',
      'eip' => '',
      'etime' => '0',
      'euser' => '',
    ),
  ),
  'p2016' => 
  array (
    'exp_s01' => 
    array (
      'kid' => 'exp_s01',
      'model' => 'cargo',
      'catid' => 'p2016',
      'title' => '营运商',
      'top' => '120',
      'enable' => '1',
      'etab' => '0',
      'type' => 'select',
      'dbtype' => 'varchar',
      'dblen' => '12',
      'dbdef' => '',
      'vreg' => '',
      'vtip' => '',
      'vmax' => '12',
      'fmsize' => '',
      'fmline' => '1',
      'fmtitle' => '0',
      'fmextra' => '',
      'fmexstr' => '',
      'cfgs' => 'yidong=移动
liantong=联通
dianxin=电信',
      'note' => '',
      'aip' => '',
      'atime' => '0',
      'auser' => '',
      'eip' => '',
      'etime' => '0',
      'euser' => '',
    ),
    'exp_s02' => 
    array (
      'kid' => 'exp_s02',
      'model' => 'cargo',
      'catid' => 'p2016',
      'title' => '网络',
      'top' => '240',
      'enable' => '1',
      'etab' => '0',
      'type' => 'select',
      'dbtype' => 'varchar',
      'dblen' => '12',
      'dbdef' => '',
      'vreg' => '',
      'vtip' => '',
      'vmax' => '12',
      'fmsize' => '',
      'fmline' => '0',
      'fmtitle' => '1',
      'fmextra' => '',
      'fmexstr' => '',
      'cfgs' => '3g=3G
2g=2G
4g=4G
cdma=CDMA',
      'note' => '',
      'aip' => '',
      'atime' => '0',
      'auser' => '',
      'eip' => '',
      'etime' => '0',
      'euser' => '',
    ),
  ),
  'p2018' => 
  array (
    'exp_s01' => 
    array (
      'kid' => 'exp_s01',
      'model' => 'cargo',
      'catid' => 'p2018',
      'title' => '上架类目',
      'top' => '120',
      'enable' => '1',
      'etab' => '0',
      'type' => 'select',
      'dbtype' => 'varchar',
      'dblen' => '12',
      'dbdef' => '',
      'vreg' => '',
      'vtip' => '',
      'vmax' => '12',
      'fmsize' => '',
      'fmline' => '1',
      'fmtitle' => '0',
      'fmextra' => '',
      'fmexstr' => '',
      'cfgs' => 'lizhi=励志类
waiwen=外文类
wenshi=文史哲
cankao=参考书
xuesheng=学生读物',
      'note' => '',
      'aip' => '',
      'atime' => '0',
      'auser' => '',
      'eip' => '',
      'etime' => '0',
      'euser' => '',
    ),
    'exp_i01' => 
    array (
      'kid' => 'exp_i01',
      'model' => 'cargo',
      'catid' => 'p2018',
      'title' => '出版社',
      'top' => '160',
      'enable' => '1',
      'etab' => '0',
      'type' => 'input',
      'dbtype' => 'varchar',
      'dblen' => '255',
      'dbdef' => '',
      'vreg' => '',
      'vtip' => '',
      'vmax' => '255',
      'fmsize' => '180',
      'fmline' => '0',
      'fmtitle' => '1',
      'fmextra' => '',
      'fmexstr' => '',
      'cfgs' => '',
      'note' => '',
      'aip' => '',
      'atime' => '0',
      'auser' => '',
      'eip' => '',
      'etime' => '0',
      'euser' => '',
    ),
    'exp_i02' => 
    array (
      'kid' => 'exp_i02',
      'model' => 'cargo',
      'catid' => 'p2018',
      'title' => '作者编辑',
      'top' => '240',
      'enable' => '1',
      'etab' => '0',
      'type' => 'input',
      'dbtype' => 'varchar',
      'dblen' => '255',
      'dbdef' => '',
      'vreg' => '',
      'vtip' => '',
      'vmax' => '255',
      'fmsize' => '360',
      'fmline' => '1',
      'fmtitle' => '0',
      'fmextra' => '',
      'fmexstr' => '',
      'cfgs' => '',
      'note' => '',
      'aip' => '',
      'atime' => '0',
      'auser' => '',
      'eip' => '',
      'etime' => '0',
      'euser' => '',
    ),
  ),
);
?>