<?php
$_c_govern = array (
  'gvip' => 
  array (
    't400' => 
    array (
      'kid' => 't400',
      'model' => 'govern',
      'catid' => 'gvip',
      'title' => '400电话',
      'top' => '666',
      'enable' => '1',
      'etab' => '0',
      'type' => 'input',
      'dbtype' => 'varchar',
      'dblen' => '24',
      'dbdef' => '',
      'vreg' => 'fix:tel',
      'vtip' => '2-24字符',
      'vmax' => '24',
      'fmsize' => '',
      'fmline' => '1',
      'fmtitle' => '0',
      'fmextra' => '',
      'fmexstr' => '',
      'cfgs' => '',
      'note' => '',
      'aip' => '',
      'atime' => '0',
      'auser' => '',
      'eip' => '',
      'etime' => '0',
      'euser' => '',
    ),
    't800' => 
    array (
      'kid' => 't800',
      'model' => 'govern',
      'catid' => 'gvip',
      'title' => '800电话',
      'top' => '888',
      'enable' => '1',
      'etab' => '0',
      'type' => 'input',
      'dbtype' => 'varchar',
      'dblen' => '24',
      'dbdef' => '',
      'vreg' => 'fix:tel',
      'vtip' => '2-24字符',
      'vmax' => '24',
      'fmsize' => '',
      'fmline' => '0',
      'fmtitle' => '1',
      'fmextra' => '',
      'fmexstr' => '',
      'cfgs' => '',
      'note' => '',
      'aip' => '',
      'atime' => '0',
      'auser' => '',
      'eip' => '',
      'etime' => '0',
      'euser' => '',
    ),
  ),
);
?>