<?php
$_china = array (
  'kid' => 'china',
  'pid' => 'types',
  'title' => '省市',
  'enable' => '1',
  'etab' => '1',
  'deep' => '2',
  'cfgs' => 'exdoc=1',
  'f' => 
  array (
    'renkou' => 
    array (
      'title' => '人口',
      'enable' => '1',
      'etab' => '0',
      'type' => 'input',
      'dbtype' => 'float',
      'dblen' => '9',
      'dbdef' => '',
      'vreg' => 'n+d',
      'vtip' => '数字,单位(万)',
      'vmax' => '12',
      'fmsize' => '',
      'fmline' => '1',
      'fmtitle' => '0',
    ),
    'mianji' => 
    array (
      'title' => '面积',
      'enable' => '1',
      'etab' => '0',
      'type' => 'input',
      'dbtype' => 'float',
      'dblen' => '12',
      'dbdef' => '',
      'vreg' => 'n+d',
      'vtip' => '数字,平方公里',
      'vmax' => '12',
      'fmsize' => '',
      'fmline' => '1',
      'fmtitle' => '0',
    ),
    'quhao' => 
    array (
      'title' => '区号',
      'enable' => '1',
      'etab' => '0',
      'type' => 'input',
      'dbtype' => 'varchar',
      'dblen' => '6',
      'dbdef' => '',
      'vreg' => '',
      'vtip' => '',
      'vmax' => '6',
      'fmsize' => '',
      'fmline' => '1',
      'fmtitle' => '0',
    ),
    'map' => 
    array (
      'title' => '坐标',
      'enable' => '1',
      'etab' => '0',
      'type' => 'input',
      'dbtype' => 'varchar',
      'dblen' => '48',
      'dbdef' => '',
      'vreg' => '',
      'vtip' => '',
      'vmax' => '48',
      'fmsize' => '240',
      'fmline' => '1',
      'fmtitle' => '0',
      'fmextra' => 'map',
    ),
  ),
  'i' => 'china',
);
?>