<?php
$_prsafe = array (
  'kid' => 'prsafe',
  'pid' => 'score',
  'title' => '安全参数',
  'enable' => '1',
  'etab' => '0',
  'deep' => '1',
  'f' => 
  array (
    'safe_site' => 
    array (
      'title' => '全站唯一随机码',
      'enable' => '1',
      'etab' => '0',
      'type' => 'input',
      'dbtype' => 'varchar',
      'dblen' => '255',
      'dbdef' => '',
      'vreg' => 'str:18-48',
      'vtip' => '18~48位',
      'vmax' => '255',
      'fmsize' => '360',
      'fmline' => '1',
      'fmtitle' => '0',
      'key' => '[safe][site]',
    ),
    'safe_pass' => 
    array (
      'title' => '密码加密-混淆码',
      'enable' => '1',
      'etab' => '0',
      'type' => 'input',
      'dbtype' => 'varchar',
      'dblen' => '255',
      'dbdef' => '',
      'vreg' => 'str:18-48',
      'vtip' => '18-48位',
      'vmax' => '255',
      'fmsize' => '360',
      'fmline' => '1',
      'fmtitle' => '0',
      'key' => '[safe][pass]',
    ),
    'safe_adminer' => 
    array (
      'title' => 'm混淆码-adminer',
      'enable' => '1',
      'etab' => '0',
      'type' => 'input',
      'dbtype' => 'varchar',
      'dblen' => '255',
      'dbdef' => '',
      'vreg' => 'str:18-48',
      'vtip' => '18-48位',
      'vmax' => '255',
      'fmsize' => '360',
      'fmline' => '1',
      'fmtitle' => '0',
      'key' => '[safe][adminer]',
    ),
    'safe_api' => 
    array (
      'title' => 'API-随即码',
      'enable' => '1',
      'etab' => '0',
      'type' => 'input',
      'dbtype' => 'varchar',
      'dblen' => '255',
      'dbdef' => '',
      'vreg' => 'str:18-48',
      'vtip' => '18~48位',
      'vmax' => '255',
      'fmsize' => '360',
      'fmline' => '1',
      'fmtitle' => '0',
      'key' => '[safe][api]',
    ),
    'safe_js' => 
    array (
      'title' => 'JS-随即码',
      'enable' => '1',
      'etab' => '0',
      'type' => 'input',
      'dbtype' => 'varchar',
      'dblen' => '255',
      'dbdef' => '',
      'vreg' => 'str:18-48',
      'vtip' => '18~48位',
      'vmax' => '255',
      'fmsize' => '360',
      'fmline' => '1',
      'fmtitle' => '0',
      'key' => '[safe][js]',
    ),
    'safe_other' => 
    array (
      'title' => 'Other-其他随机码',
      'enable' => '1',
      'etab' => '0',
      'type' => 'input',
      'dbtype' => 'varchar',
      'dblen' => '255',
      'dbdef' => '',
      'vreg' => 'str:18-48',
      'vtip' => '18~48位',
      'vmax' => '255',
      'fmsize' => '360',
      'fmline' => '1',
      'fmtitle' => '0',
      'key' => '[safe][other]',
    ),
    'safe_safil' => 
    array (
      'title' => '安全过滤-随机码',
      'enable' => '1',
      'etab' => '0',
      'type' => 'input',
      'dbtype' => 'varchar',
      'dblen' => '255',
      'dbdef' => '',
      'vreg' => 'str:18-48',
      'vtip' => '18~48位',
      'vmax' => '255',
      'fmsize' => '360',
      'fmline' => '1',
      'fmtitle' => '0',
      'key' => '[safe][safil]',
    ),
    'safe_safix' => 
    array (
      'title' => '安全过滤-数组前缀',
      'enable' => '1',
      'etab' => '0',
      'type' => 'input',
      'dbtype' => 'varchar',
      'dblen' => '255',
      'dbdef' => '',
      'vreg' => 'str:4-4',
      'vtip' => '4位',
      'vmax' => '4',
      'fmsize' => '360',
      'fmline' => '1',
      'fmtitle' => '0',
      'key' => '[safe][safix]',
    ),
    'safe_rnum' => 
    array (
      'title' => '数字-随机码',
      'enable' => '1',
      'etab' => '0',
      'type' => 'input',
      'dbtype' => 'varchar',
      'dblen' => '255',
      'dbdef' => '',
      'vreg' => 'str:18-48',
      'vtip' => '18~48位',
      'vmax' => '255',
      'fmsize' => '360',
      'fmline' => '1',
      'fmtitle' => '0',
      'key' => '[safe][rnum]',
    ),
    'safe_rspe' => 
    array (
      'title' => '特殊字符-随机码',
      'enable' => '1',
      'etab' => '0',
      'type' => 'input',
      'dbtype' => 'varchar',
      'dblen' => '255',
      'dbdef' => '',
      'vreg' => 'str:18-48',
      'vtip' => '18~48位',
      'vmax' => '255',
      'fmsize' => '360',
      'fmline' => '1',
      'fmtitle' => '0',
      'key' => '[safe][rspe]',
    ),
    'safe_rndch6' => 
    array (
      'title' => '随机6位码',
      'enable' => '1',
      'etab' => '0',
      'type' => 'input',
      'dbtype' => 'varchar',
      'dblen' => '6',
      'dbdef' => '',
      'vreg' => '',
      'vtip' => '',
      'vmax' => '6',
      'fmsize' => '',
      'fmline' => '1',
      'fmtitle' => '0',
      'key' => '[safe][rndch6]',
    ),
    'safe_rndtab' => 
    array (
      'title' => '随机62位不重复码',
      'enable' => '1',
      'etab' => '0',
      'type' => 'input',
      'dbtype' => 'varchar',
      'dblen' => '62',
      'dbdef' => '',
      'vreg' => '',
      'vtip' => '',
      'vmax' => '62',
      'fmsize' => '360',
      'fmline' => '1',
      'fmtitle' => '0',
      'key' => '[safe][rndtab]',
    ),
    'tout_admin' => 
    array (
      'title' => '管理后台_超时时间',
      'enable' => '1',
      'etab' => '0',
      'type' => 'input',
      'dbtype' => 'int',
      'dblen' => '255',
      'dbdef' => '1200',
      'vreg' => 'n+i',
      'vtip' => '单位(秒),建议1200~3600之间',
      'vmax' => '12',
      'fmsize' => '',
      'fmline' => '1',
      'fmtitle' => '0',
      'key' => 'tout_admin',
    ),
    'tout_member' => 
    array (
      'title' => '会员_超时时间',
      'enable' => '1',
      'etab' => '0',
      'type' => 'input',
      'dbtype' => 'int',
      'dblen' => '255',
      'dbdef' => '2400',
      'vreg' => 'n+i',
      'vtip' => '建议1200~3600之间(秒)',
      'vmax' => '12',
      'fmsize' => '',
      'fmline' => '1',
      'fmtitle' => '0',
      'key' => 'tout_member',
    ),
  ),
);
?>