<?php
$_prshow = array (
  'kid' => 'prshow',
  'pid' => 'score',
  'title' => '显示参数',
  'enable' => '1',
  'etab' => '0',
  'deep' => '1',
  'f' => 
  array (
    'show_apsize' => 
    array (
      'title' => '后台资料列表每页资料数',
      'enable' => '1',
      'etab' => '0',
      'type' => 'input',
      'dbtype' => 'int',
      'dblen' => '10',
      'dbdef' => '',
      'vreg' => '',
      'vtip' => '',
      'vmax' => '10',
      'fmsize' => '',
      'fmline' => '1',
      'fmtitle' => '0',
      'key' => '[show][apsize]',
    ),
    'show_mpsize' => 
    array (
      'title' => '会员中心列表每页资料数',
      'enable' => '1',
      'etab' => '0',
      'type' => 'input',
      'dbtype' => 'int',
      'dblen' => '10',
      'dbdef' => '',
      'vreg' => '',
      'vtip' => '',
      'vmax' => '10',
      'fmsize' => '',
      'fmline' => '1',
      'fmtitle' => '0',
      'key' => '[show][mpsize]',
    ),
    'show_fpsize' => 
    array (
      'title' => '前台资料列表每页资料数',
      'enable' => '1',
      'etab' => '0',
      'type' => 'input',
      'dbtype' => 'int',
      'dblen' => '10',
      'dbdef' => '20',
      'vreg' => '',
      'vtip' => '',
      'vmax' => '10',
      'fmsize' => '',
      'fmline' => '1',
      'fmtitle' => '0',
      'key' => '[show][fpsize]',
    ),
    'show_ppsize' => 
    array (
      'title' => '资料选取列表每页资料数',
      'enable' => '1',
      'etab' => '0',
      'type' => 'input',
      'dbtype' => 'int',
      'dblen' => '10',
      'dbdef' => '',
      'vreg' => '',
      'vtip' => '',
      'vmax' => '10',
      'fmsize' => '',
      'fmline' => '1',
      'fmtitle' => '0',
      'key' => '[show][ppsize]',
    ),
  ),
);
?>